"""Canonical registry of all 100 inventions with import paths + status."""

from __future__ import annotations

from typing import Any

INVENTIONS: list[dict[str, Any]] = [
    {"id": 1, "name": "BINDLOCK", "status": "coded", "path": "utils.generation.inventions.bindlock"},
    {"id": 2, "name": "COUNTGATE", "status": "coded", "path": "utils.generation.inventions.countgate"},
    {"id": 3, "name": "NEGATRON", "status": "coded", "path": "utils.generation.inventions.negatron"},
    {"id": 4, "name": "HYDRA-SLOTS", "status": "coded", "path": "utils.generation.inventions.hydra_slots"},
    {"id": 5, "name": "SAT-LAYOUT", "status": "coded", "path": "utils.generation.inventions.composition_ext"},
    {"id": 6, "name": "RelationTransformerHead", "status": "coded", "path": "models.inventions_arch"},
    {"id": 7, "name": "ConceptAlgebraLoss", "status": "coded", "path": "models.inventions_arch"},
    {"id": 8, "name": "NegationTokenBank", "status": "coded", "path": "models.inventions_arch"},
    {"id": 9, "name": "CountClassToken", "status": "coded", "path": "models.inventions_arch"},
    {"id": 10, "name": "AttributeFirewallMask", "status": "coded", "path": "models.inventions_arch"},
    {"id": 11, "name": "SceneGraph", "status": "coded", "path": "utils.generation.inventions.composition_ext"},
    {"id": 12, "name": "AntiCentering", "status": "coded", "path": "utils.generation.inventions.composition_ext"},
    {"id": 13, "name": "ZOrder", "status": "coded", "path": "utils.generation.inventions.composition_ext"},
    {"id": 14, "name": "OcclusionGrammar", "status": "coded", "path": "utils.generation.inventions.composition_ext"},
    {
        "id": 15,
        "name": "MultiplicityCurriculum",
        "status": "coded",
        "path": "utils.generation.inventions.composition_ext",
    },
    {"id": 16, "name": "BindingContrastive", "status": "coded", "path": "utils.generation.inventions.composition_ext"},
    {"id": 17, "name": "LayoutDiffusionPrior", "status": "coded", "path": "models.inventions_arch"},
    {"id": 18, "name": "NeuroSymbolicCFG", "status": "coded", "path": "utils.generation.inventions.composition_ext"},
    {"id": 19, "name": "FailureAtlas", "status": "coded", "path": "utils.generation.inventions.composition_ext"},
    {"id": 20, "name": "ORACLE", "status": "coded", "path": "utils.generation.inventions.failure_oracle"},
    {"id": 21, "name": "ANATOMON", "status": "coded", "path": "utils.generation.inventions.anatomon"},
    {"id": 22, "name": "HandExpert", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {
        "id": 23,
        "name": "MeshGuidedDenoise",
        "status": "scaffold",
        "path": "utils.generation.inventions.anatomy_ext",
        "note": "hook via pose_skeleton_soft + future SMPL",
    },
    {"id": 24, "name": "FingerCritic", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 25, "name": "LimbMonotonicityLoss", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 26, "name": "PoseSkeletonSoft", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 27, "name": "FaceIdExpression", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 28, "name": "EyeSymmetryBreaker", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 29, "name": "TeethMouth", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 30, "name": "ContactShadow", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 31, "name": "AnatomyRLHF", "status": "scaffold", "path": "scripts.tools.ops.preference_flywheel"},
    {
        "id": 32,
        "name": "PartAwareVAE",
        "status": "scaffold",
        "path": "models.inventions_arch",
        "note": "capacity split design only",
    },
    {"id": 33, "name": "AnatomyTokenVocab", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 34, "name": "TwoStageBodyDetail", "status": "coded", "path": "utils.generation.inventions.anatomy_ext"},
    {"id": 35, "name": "CONSENSUS", "status": "coded", "path": "utils.generation.inventions.consensus_denoise"},
    {"id": 36, "name": "FRICTION", "status": "coded", "path": "utils.generation.inventions.friction_texture"},
    {"id": 37, "name": "SPECTRA", "status": "coded", "path": "utils.generation.inventions.spectra_routing"},
    {"id": 38, "name": "LensEXIF", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 39, "name": "DemosaicRealism", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 40, "name": "SensorNoise", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 41, "name": "BRDFTokens", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 42, "name": "SSSHint", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 43, "name": "AsymmetryLottery", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 44, "name": "JPEGSpice", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 45, "name": "HistogramMatch", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 46, "name": "FilmicHighlights", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 47, "name": "GrimeCorners", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 48, "name": "AntiBeautyFilter", "status": "coded", "path": "utils.generation.inventions.texture_ext"},
    {"id": 49, "name": "GlyphRouting", "status": "coded", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 50, "name": "OCRGlyphLoop", "status": "coded", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 51, "name": "BezierText", "status": "coded", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 52, "name": "FontID", "status": "coded", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 53, "name": "IdeogramLayout", "status": "coded", "path": "utils.generation.edit_skills"},
    {"id": 54, "name": "BrandKit", "status": "coded", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 55, "name": "KerningLoss", "status": "scaffold", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 56, "name": "MultilingualGlyph", "status": "coded", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 57, "name": "UIScreenshot", "status": "coded", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 58, "name": "VectorExport", "status": "coded", "path": "utils.generation.inventions.glyph_ext"},
    {"id": 59, "name": "CastCompiler", "status": "coded", "path": "utils.generation.multi_char_cast"},
    {"id": 60, "name": "PerCharRefs", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {
        "id": 61,
        "name": "MultiCharConditionerWire",
        "status": "coded",
        "path": "utils.generation.inventions.identity_ext",
    },
    {"id": 62, "name": "ClothingOwnershipMask", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {"id": 63, "name": "InteractionPhysics", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {"id": 64, "name": "IdentityPermanence", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {"id": 65, "name": "AutoCharacterSheet", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {"id": 66, "name": "VoiceToLook", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {"id": 67, "name": "AntiTwin", "status": "coded", "path": "utils.generation.multi_char_cast"},
    {"id": 68, "name": "SlotDropout", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {"id": 69, "name": "CrossCharContrastive", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {"id": 70, "name": "CastMemory", "status": "coded", "path": "utils.generation.inventions.identity_ext"},
    {"id": 71, "name": "CorpusRetrieve", "status": "coded", "path": "utils.generation.corpus_retrieve"},
    {"id": 72, "name": "CLIPFAISS", "status": "coded", "path": "utils.generation.inventions.data_ext"},
    {
        "id": 73,
        "name": "ArtistStylePack",
        "status": "partial",
        "path": "scripts.tools.training.train_style_lora_oneshot",
    },
    {"id": 74, "name": "RatingFilter", "status": "coded", "path": "utils.generation.inventions.data_ext"},
    {"id": 75, "name": "TagCanonicalizer", "status": "coded", "path": "utils.generation.inventions.data_ext"},
    {"id": 76, "name": "HardNegativeMine", "status": "coded", "path": "utils.generation.inventions.data_ext"},
    {
        "id": 77,
        "name": "SyntheticConstraints",
        "status": "coded",
        "path": "utils.generation.inventions.composition_ext",
    },
    {"id": 78, "name": "ArtistUpweight", "status": "coded", "path": "utils.generation.inventions.data_ext"},
    {"id": 79, "name": "PerceptualDedup", "status": "coded", "path": "utils.generation.inventions.data_ext"},
    {"id": 80, "name": "PreferenceFlywheel", "status": "partial", "path": "scripts.tools.ops.preference_flywheel"},
    {"id": 81, "name": "APEX", "status": "coded", "path": "diffusion.solvers.apex"},
    {"id": 82, "name": "CONSENSUS", "status": "coded", "path": "utils.generation.inventions.consensus_denoise"},
    {"id": 83, "name": "OracleSearchRungs", "status": "coded", "path": "utils.generation.inventions.systems_ext"},
    {
        "id": 84,
        "name": "SpeculativeCFG+SPECTRA",
        "status": "coded",
        "path": "utils.generation.inventions.spectra_routing",
    },
    {"id": 85, "name": "ErrorRedo", "status": "coded", "path": "utils.generation.inventions.systems_ext"},
    {"id": 86, "name": "AdaptiveNFE", "status": "coded", "path": "utils.generation.inventions.systems_ext"},
    {"id": 87, "name": "FlowVPHandoff", "status": "coded", "path": "utils.generation.inventions.systems_ext"},
    {"id": 88, "name": "APEXDistill", "status": "coded", "path": "utils.generation.inventions.systems_ext"},
    {"id": 89, "name": "ParallelExperts", "status": "coded", "path": "utils.generation.inventions.systems_ext"},
    {"id": 90, "name": "EnergyReject", "status": "coded", "path": "utils.generation.inventions.systems_ext"},
    {"id": 91, "name": "ObjectCentricDiT", "status": "coded", "path": "models.inventions_arch"},
    {"id": 92, "name": "ConstraintDiffusion", "status": "coded", "path": "models.inventions_arch"},
    {"id": 93, "name": "GlyphNativeTokenizer", "status": "coded", "path": "models.inventions_arch"},
    {"id": 94, "name": "PhysicsContact", "status": "coded", "path": "models.inventions_arch"},
    {"id": 95, "name": "WorldModelTriplane", "status": "partial", "path": "frontier.multiview"},
    {"id": 96, "name": "CausalEditGraph", "status": "coded", "path": "models.inventions_arch"},
    {"id": 97, "name": "DreamCritic", "status": "coded", "path": "models.inventions_arch"},
    {"id": 98, "name": "MemoryAugmentedKV", "status": "coded", "path": "models.inventions_arch"},
    {"id": 99, "name": "BlockARHybrid", "status": "partial", "path": "models.attention"},
    {"id": 100, "name": "SelfHealingLoop", "status": "coded", "path": "utils.generation.inventions.systems_ext"},
]


def inventory() -> dict[str, int]:
    from collections import Counter

    return dict(Counter(i["status"] for i in INVENTIONS))


def get_invention(i: int) -> dict[str, Any] | None:
    for row in INVENTIONS:
        if row["id"] == i:
            return row
    return None
