"""Export minimal ComfyUI workflow JSON for SDX sample settings."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Mapping


def sample_args_to_comfy_workflow(
    args: Mapping[str, Any],
    *,
    title: str = "SDX Export",
) -> Dict[str, Any]:
    """Build a portable Comfy-style node graph (API-loadable skeleton)."""
    ckpt = str(args.get("ckpt", "results/best.pt"))
    prompt = str(args.get("prompt", ""))
    negative = str(args.get("negative_prompt", ""))
    steps = int(args.get("steps", 50))
    cfg = float(args.get("cfg_scale", 7.5))
    seed = int(args.get("seed", 42))
    w = int(args.get("width", 0) or 1024)
    h = int(args.get("height", 0) or 1024)

    return {
        "version": "sdx-comfy-export-1",
        "title": title,
        "notes": "Generated by SDX — map CheckpointLoader to your Comfy DiT/SDX bridge node.",
        "nodes": {
            "1": {
                "class_type": "SDXLoadCheckpoint",
                "inputs": {"ckpt_path": ckpt},
            },
            "2": {
                "class_type": "CLIPTextEncode",
                "inputs": {"text": prompt},
            },
            "3": {
                "class_type": "CLIPTextEncode",
                "inputs": {"text": negative},
            },
            "4": {
                "class_type": "SDXSampler",
                "inputs": {
                    "steps": steps,
                    "cfg": cfg,
                    "seed": seed,
                    "width": w,
                    "height": h,
                    "box_layout": str(args.get("box_layout", "") or ""),
                    "holy_grail": bool(args.get("holy_grail", False)),
                    "frontier": bool(args.get("frontier", False)),
                },
            },
            "5": {"class_type": "SaveImage", "inputs": {"filename_prefix": "sdx_export"}},
        },
        "links": [
            ["1", 0, "4", 0],
            ["2", 0, "4", 1],
            ["3", 0, "4", 2],
            ["4", 0, "5", 0],
        ],
    }


def write_comfy_workflow(path: str | Path, workflow: Dict[str, Any]) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(workflow, indent=2), encoding="utf-8")
    return p
