"""
Top trigger tokens from ``data/civitai/nsfw_illustrious_noobai_models.csv`` (frequency-ranked).

Regenerate after refreshing the CSV::

    python scripts/tools/curate_civitai_triggers.py
"""

from __future__ import annotations

# Regenerate: python scripts/tools/curate_civitai_triggers.py
CIVITAI_HOT_TAGS = [
    '1girl',
    'long hair',
    'solo',
    'large breasts',
    'short hair',
    'blue eyes',
    'cleavage',
    'black hair',
    'long sleeves',
    'bare shoulders',
    'blonde hair',
    'navel',
    'brown hair',
    '1boy',
    'brown eyes',
    'jewelry',
    'skirt',
    'white shirt',
    'bangs',
    'gloves',
    'green eyes',
    'hair ornament',
    'thighhighs',
    'red eyes',
    'purple eyes',
    'breasts',
    'belt',
    'medium breasts',
    'looking at viewer',
    'ponytail',
    'earrings',
    'dress',
    'pleated skirt',
    'nipples',
    'hair between eyes',
    'anime screencap',
    'midriff',
    'boots',
    'detached sleeves',
    'shirt',
    'penis',
    'white hair',
    'furry',
    'black eyes',
    'black thighhighs',
    'black gloves',
    'very long hair',
    'yellow eyes',
    'fingerless gloves',
    'lips',
    'blush',
    'short sleeves',
    'standing',
    'sidelocks',
    'elbow gloves',
    'necklace',
    'choker',
    'school uniform',
    'twintails',
    'nude',
    'collarbone',
    'pink hair',
    'purple hair',
    'hetero',
    'clothing cutout',
    'pussy',
    'white dress',
    'blue hair',
    'high heels',
    'red hair',
    'fellatio',
    'mature female',
    'pov',
    'thigh strap',
    'jacket',
    'animal ears',
    'sex',
    'multicolored hair',
    'smile',
    'open mouth',
    'white gloves',
    'tail',
    'pointy ears',
    'pantyhose',
    'miniskirt',
    'black footwear',
    'ahoge',
    'collared shirt',
    'hair ribbon',
    'thigh boots',
    'black skirt',
    'black dress',
    'open clothes',
    'sleeveless',
    'solo focus',
    'bow',
    'white thighhighs',
    'thick thighs',
    'huge breasts',
    'cleavage cutout',
    'furry female',
    'realistic',
    '3d',
    'glasses',
    'japanese clothes',
    'crop top',
    'bracelet',
    'pants',
    'wide hips',
    'cum',
    'makeup',
    'curvy',
    'horns',
    'lipstick',
    'uncensored',
    'frills',
    'oral',
    'blunt bangs',
    'sweat',
    'heels',
    'medium hair',
    'shoes',
    'braid',
    'grey hair',
    'anthro',
    'vaginal',
    'anime coloring',
    'colored skin',
    'armor',
    'ass',
    'ribbon',
    'dark-skinned female',
    'collar',
    'barefoot',
    'underwear',
    'pink eyes',
    'hairband',
    'lying',
    'completely nude',
    'testicles',
    'small breasts',
    'black choker',
    'black pantyhose',
    'black shirt',
    'spread legs',
    'black jacket',
    'full body',
    'wide sleeves',
    'blue skirt',
    'hair bow',
]
