"""
Prompt controls for harder generation targets.

This module helps with:
- SFW/NSFW intent stabilization (clean SFW packs vs explicit NSFW scaffolding)
- one-shot style scaffolding: clear subject, anatomy, composition, lighting coherence
- prompt adherence packs (standard/strict) and micro-detail quality for texture/material readout
- de-AI / human-media packs (anti plastic-CGI, photographic vs film vs DSLR cues)
- LoRA fusion scaffolding (blend vs character-first vs style-first)
- complex poses and difficult camera/view angles
- object/vehicle/building grounding
- suppressing unwanted text/logos/watermarks when text is not desired
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

from .civitai_vocab import CIVITAI_HOT_TAGS

# Short tags mined from CSV trigger fragments + shortened model-name phrases (not full titles).
# Deduped against CIVITAI_HOT_TAGS + score/quality tokens. Regenerate: ``extract_civitai_snippets_for_content_controls.py``.
_CIVITAI_SNIPPET_TAGS: List[str] = [
    "hat",
    "white skirt",
    "black pants",
    "hair flower",
    "garter straps",
    "green hair",
    "hairclip",
    "open jacket",
    "shorts",
    "puffy sleeves",
    "bodysuit",
    "dark skin",
    "fur trim",
    "necktie",
    "swimsuit",
    "leotard",
    "hair over one eye",
    "tongue out",
    "short shorts",
    "off shoulder",
    "grey eyes",
    "thighs",
    "red dress",
    "sash",
    "sitting",
    "demon girl",
    "sleeveless dress",
    "short dress",
    "pencil skirt",
    "revealing clothes",
    "zettai ryouiki",
    "pelvic curtain",
    "blue dress",
    "sandals",
    "indoors",
    "erection",
    "parted bangs",
    "on back",
    "demon tail",
    "socks",
    "panties",
    "sex from behind",
    "chinese clothes",
    "wings",
    "white footwear",
    "anus",
    "turtleneck",
    "from side",
    "black shorts",
    "black belt",
    "bowtie",
    "demon horns",
    "halterneck",
    "upper body",
    "long_hair",
    "orange hair",
    "tongue",
    "nose",
    "red skirt",
    "knee boots",
    "covered navel",
    "saliva",
    "eyelashes",
    "retro artstyle",
    "detached collar",
    "monster girl",
    "bikini",
    "red lips",
    "strapless",
    "side slit",
    "white fur",
    "cape",
    "torn clothes",
    "white jacket",
    "hair bun",
    "maid headdress",
    "male focus",
    "gradient hair",
    "see-through",
    "red ribbon",
    "claws",
    "gold trim",
    "closed eyes",
    "plaid skirt",
    "group sex",
    "cowboy shot",
    "cum in pussy",
    "muscular",
    "military uniform",
    "cat ears",
    "white socks",
    "closed mouth",
    "animal nose",
    "shoulder armor",
    "kimono",
    "frilled dress",
]

# Default bank: generated by scripts/tools/fetch_civitai_nsfw_concepts.py (Civitai public API).
_DEFAULT_CIVITAI_MODEL_BANK_CSV = Path(__file__).resolve().parents[2] / "data" / "civitai" / "nsfw_illustrious_noobai_models.csv"
# One trigger per line, frequency order — from scripts/tools/curate_civitai_triggers.py
_DEFAULT_CIVITAI_FREQ_TXT = Path(__file__).resolve().parents[2] / "data" / "civitai" / "top_triggers_by_frequency.txt"

_CIVITAI_TRIGGER_BANK_CAPS: Dict[str, int] = {
    "none": 0,
    # CSV row order (first-seen as models appear in the API list)
    "light": 120,
    "medium": 300,
    "heavy": 600,
    # Same caps but tokens from frequency-ranked file (stronger Danbooru-style prior)
    "frequency_light": 150,
    "frequency_medium": 350,
    "frequency_heavy": 600,
}


def load_civitai_model_bank_triggers(
    csv_path: Optional[Path | str] = None,
    *,
    max_tokens: int = 120,
) -> List[str]:
    """
    Load unique trigger tokens from a Civitai model bank CSV (id,name,type,bases,triggers).

    Triggers column uses ``|``-separated tokens as written by ``fetch_civitai_nsfw_concepts.py``.
    Order is stable (first-seen wins). Empty / missing file returns [].
    """
    cap = max(0, int(max_tokens))
    if cap == 0:
        return []
    path = Path(csv_path) if csv_path is not None else _DEFAULT_CIVITAI_MODEL_BANK_CSV
    if not path.is_file():
        return []
    out: List[str] = []
    seen: set[str] = set()
    try:
        with path.open(newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                raw = (row.get("triggers") or "").strip()
                if not raw:
                    continue
                for tok in raw.split("|"):
                    t = tok.strip()
                    if not t or t in seen:
                        continue
                    seen.add(t)
                    out.append(t)
                    if len(out) >= cap:
                        return out
    except OSError:
        return []
    return out


def load_civitai_frequency_triggers(
    txt_path: Optional[Path | str] = None,
    *,
    max_tokens: int = 200,
) -> List[str]:
    """
    Load triggers from ``top_triggers_by_frequency.txt`` (one token per line, most common first).

    Regenerate that file with ``python scripts/tools/curate_civitai_triggers.py``.
    """
    cap = max(0, int(max_tokens))
    if cap == 0:
        return []
    path = Path(txt_path) if txt_path is not None else _DEFAULT_CIVITAI_FREQ_TXT
    if not path.is_file():
        return []
    out: List[str] = []
    seen: set[str] = set()
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            t = line.strip()
            if not t or t.startswith("#"):
                continue
            k = t.lower()
            if k in seen:
                continue
            seen.add(k)
            out.append(t)
            if len(out) >= cap:
                break
    except OSError:
        return []
    return out


# High-signal tags for Illustrious / Pony-style checkpoints, SDXL, and Danbooru-style prompts.
# (Score ladder is widely trained on Civitai Illustrious & Pony merges; harmless if ignored by a base model.)
_BEST_MODEL_TAGS: List[str] = [
    "score_9",
    "score_8_up",
    "score_7_up",
    "masterpiece",
    "best quality",
    "amazing quality",
    "newest",
    "absurdres",
    "highres",
    "extremely detailed",
    "ultra detailed",
    "detailed eyes",
    "detailed face",
    "detailed hair",
    "detailed skin",
    "detailed hands",
    "detailed background",
    "fine details",
    "intricate details",
    "sharp focus",
    "volumetric lighting",
    "cinematic lighting",
    "professional lighting",
    "rim lighting",
    "soft shadows",
    "depth of field",
    "dynamic composition",
    "rule of thirds",
    "rich colors",
    "vivid colors",
    "high contrast",
    "film grain subtle",
    "chromatic aberration subtle",
]


# SFW-only positives: quality + wholesome framing (no NSFW pose/toy/clothing tags).
_SFW_POSITIVE = [
    "sfw",
    "safe for work",
    "tasteful",
    "non-explicit",
    "wholesome presentation",
    "clean composition",
    "clear focal subject",
    "single coherent scene",
    "readable pose",
    "balanced composition",
    "expressive eyes",
    "natural skin texture",
    "storytelling moment",
    "atmospheric depth",
    "environment harmony",
    *_BEST_MODEL_TAGS,
    "beautiful lighting",
    "coherent colors",
    "elegant",
    "graceful",
    "serene mood",
    "peaceful atmosphere",
    "heartwarming",
    "uplifting",
    "artistic",
    "emotional depth",
    "kawaii aesthetic",
    "cute charm",
    "character focus",
    "detailed clothing folds",
    "detailed background",
    "concept art",
    "style consistent",
    "cinematic composition",
    "professional finish",
    "soft diffused light",
    "warm inviting tones",
    "pastel palette",
    "dreamy atmosphere",
    "idyllic scene",
]

_SFW_NEGATIVE = [
    "nsfw",
    "explicit nudity",
    "sexual content",
    "nipples visible",
    "genitals",
    "intercourse",
    "pornographic",
    "nude",
    "naked",
    "fully nude",
    "lewd",
    "erotic",
    "porn",
    "hentai",
    "censored",
    "deformed",
    "bad anatomy",
    "bad proportions",
    "extra limbs",
    "malformed hands",
    "extra fingers",
    "fused fingers",
    "ugly",
    "low quality",
    "blurry",
    "grainy",
    "jpeg artifacts",
    "oversaturated",
    "distorted",
    "grotesque",
    "sexualized minor",
    "duplicate person",
    "cloned face",
    "double head",
    "watermark",
    "text overlay",
    "cropped head",
    "out of frame",
    "muddy details",
]

# === LARGE SFW EXPANSION ===
_SFW_MOOD_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "wholesome": ["wholesome", "heartwarming", "pure", "innocent", "gentle", "kind"],
    "heroic": ["heroic", "brave", "determined", "epic", "inspirational", "noble"],
    "serene": ["serene", "peaceful", "calm", "tranquil", "meditative", "zen"],
    "adventurous": ["adventurous", "curious", "exploratory", "wonder", "brave explorer"],
    "joyful": ["joyful", "happy", "bright", "cheerful", "uplifting", "radiant"],
    "cozy": ["cozy", "warm", "comforting", "homey", "intimate", "safe"],
    "wonder": ["wonder", "magical", "enchanted", "dreamy", "fantastical"],
    "kawaii": ["kawaii", "cute", "adorable", "chibi style", "pastel aesthetic"],
    "storybook": ["storybook illustration", "fairytale atmosphere", "soft lighting", "dreamlike"],
}

_SFW_POSE_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "elegant": ["elegant pose", "graceful posture", "poised", "refined stance", "ballet pose"],
    "heroic": ["heroic pose", "confident stance", "powerful presence", "dynamic hero pose"],
    "contemplative": ["contemplative pose", "thoughtful expression", "introspective", "reading pose"],
    "playful": ["playful pose", "joyful movement", "lighthearted", "jumping for joy"],
    "dynamic": ["dynamic pose", "action pose", "energetic", "running pose", "dancing pose"],
    "relaxed": ["relaxed pose", "natural posture", "comfortable", "sitting peacefully"],
    "graceful": ["graceful movement", "flowing pose", "artistic stance"],
    "cute": ["cute pose", "kawaii pose", "head tilt", "peace sign", "heart hands"],
}

_SFW_CLOTHING_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "casual": ["casual clothes", "everyday wear", "t-shirt and jeans", "hoodie", "sundress"],
    "elegant": ["elegant gown", "formal dress", "evening gown", "sophisticated attire"],
    "cozy": ["cozy sweater", "warm cardigan", "comfortable loungewear", "fluffy robe"],
    "adventurer": ["adventurer outfit", "travel clothes", "explorer attire", "leather jacket"],
    "fantasy": ["fantasy robes", "mage robes", "elven clothing", "princess dress"],
    "historical": ["historical dress", "victorian clothing", "renaissance attire", "kimono"],
    "sporty": ["sporty wear", "athletic outfit", "activewear", "yoga clothes"],
    "cute": ["cute outfit", "kawaii fashion", "pastel clothes", "school uniform", "maid outfit"],
    "kawaii": ["kawaii outfit", "lolita dress", "pastel goth", "cute accessories"],
}

_SFW_ENVIRONMENT_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "forest": ["peaceful forest", "sunlit woods", "enchanted forest", "autumn forest"],
    "cabin": ["cozy cabin", "warm fireplace", "rustic interior", "mountain cabin"],
    "meadow": ["sunlit meadow", "flower field", "rolling hills", "wildflower meadow"],
    "library": ["grand library", "quiet study", "bookshelves", "ancient library"],
    "garden": ["beautiful garden", "flower garden", "zen garden", "rose garden"],
    "night": ["starry night sky", "moonlit landscape", "gentle night", "aurora sky"],
    "studio": ["art studio", "painting studio", "warm workshop", "creative space"],
}

# === LARGE NSFW EXPANSION FROM CIVITAI ===
# "hits" / "hits_lite": frequency-mined from Illustrious+NoobAI NSFW CSV (see civitai_vocab.CIVITAI_HOT_TAGS).
_NSFW_CIVITAI_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "hits": list(CIVITAI_HOT_TAGS),
    "hits_lite": list(CIVITAI_HOT_TAGS[:48]),
    "snippets": list(_CIVITAI_SNIPPET_TAGS),
    "snippets_lite": list(_CIVITAI_SNIPPET_TAGS[:36]),
    "action": ["action pose", "dynamic action", "fighting pose", "dancing pose", "running pose", "jumping pose"],
    "complex": ["shibari pose", "suspended pose", "piledriver pose", "full nelson", "mating press", "amazon position", "reverse cowgirl", "all fours", "kneeling blowjob", "squatting cowgirl", "split leg missionary"],
    "easy": ["missionary position", "doggy style", "cowgirl position", "standing sex", "spooning sex", "face sitting", "69", "lotus position"],
    "clothing": ["latex catsuit", "pvc dress", "leather harness", "cage harness", "open cup bra", "crotchless panties", "bunny suit", "gothic lolita", "succubus outfit", "demon outfit", "angel corruption", "maid outfit nsfw", "school uniform nsfw"],
    "objects": ["onahole", "fleshlight", "automatic stroker", "suction cup dildo", "rabbit vibrator", "wand massager", "nipple clamps", "ball gag", "blindfold", "bondage rope", "spanking paddle", "anal beads", "butt plug", "strap on", "tentacle toy", "magic wand"],
    "style": ["ahegao", "mind break", "pleasure overload", "throat bulge", "belly bulge", "cum on face", "creampie", "squirting", "glossy wet skin", "detailed pussy", "veiny thick cock", "puffy wet pussy"],
}

_NSFW_CIVITAI_NEGATIVE: Dict[str, List[str]] = {
    "none": [],
    "hits": [
        "wrong eye color",
        "mismatched outfit tags",
        "tag soup artifact",
        "incoherent anatomy with crowd tags",
        "extra limbs",
        "bad hands",
    ],
    "hits_lite": [
        "wrong eye color",
        "extra limbs",
        "bad hands",
    ],
    "snippets": [
        "contradictory outfit tags",
        "tag collision",
        "incoherent props",
        "wrong horn count",
        "broken costume geometry",
    ],
    "snippets_lite": [
        "contradictory outfit tags",
        "tag collision",
        "broken costume geometry",
    ],
    "action": ["bad anatomy", "extra limbs", "floating body", "deformed pose"],
    "complex": ["censorship bars", "mosaic censor", "blurred private parts", "impossible anatomy", "fused bodies"],
    "clothing": ["melted clothing", "fused fabric", "broken straps", "plastic looking outfit"],
    "objects": ["floating toy", "broken toy", "warped dildo", "missing object"],
    "style": ["flat expression", "dead eyes", "no emotion", "plastic skin", "bad lighting"],
}

_SFW_EXPRESSION_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "gentle": ["gentle smile", "soft expression", "kind eyes"],
    "joyful": ["joyful smile", "happy expression", "bright eyes"],
    "curious": ["curious expression", "wondering look", "thoughtful gaze"],
    "serene": ["serene expression", "peaceful face", "calm demeanor"],
    "determined": ["determined look", "focused expression", "confident"],
}

_NSFW_POSITIVE = [
    "nsfw",
    "adult content",
    "anatomically coherent",
    "clear body structure",
    "detailed anatomy",
    "natural proportions",
    "explicit detail",
    "uncensored",
    "single clear subject",
    "coherent pose",
    "readable silhouettes",
    "grounded lighting on body",
    "eye contact clarity",
    "natural skin texture",
    "complete figure in frame",
    *_BEST_MODEL_TAGS,
]

_NSFW_NEGATIVE = [
    "censorship bars",
    "mosaic censor",
    "cropped anatomy",
    "sfw",
    "censored",
    "bar over",
    "pixelated",
    "blurred private parts",
    "bad hands",
    "mutated hands",
    "extra fingers",
    "fused fingers",
    "duplicate body",
    "cloned face",
    "fused bodies",
    "incoherent pose",
    "muddy low contrast",
    "blurry face",
    "worst quality",
    "low quality",
]

_POSE_POSITIVE: Dict[str, List[str]] = {
    "complex": [
        "dynamic full-body pose",
        "balanced anatomy",
        "clear limb placement",
        "foreshortening",
    ],
    "action": [
        "action pose",
        "dynamic motion",
        "clear body mechanics",
        "balanced center of gravity",
    ],
    "acrobatics": [
        "acrobatic pose",
        "extreme perspective pose",
        "clear limb articulation",
        "anatomical coherence",
    ],
}
_POSE_NEGATIVE = [
    "broken limbs",
    "disconnected joints",
    "extra arms",
    "extra legs",
    "twisted anatomy",
]

_ANGLE_POSITIVE: Dict[str, List[str]] = {
    "eye_level": ["eye-level shot", "natural perspective"],
    "low_angle": ["low-angle shot", "upward perspective", "correct foreshortening"],
    "high_angle": ["high-angle shot", "top-down perspective"],
    "bird_eye": ["bird's-eye view", "overhead shot", "coherent top-down geometry"],
    "worm_eye": ["worm's-eye view", "extreme low-angle perspective"],
    "dutch": ["dutch angle", "tilted camera", "intentional composition tilt"],
    "over_shoulder": ["over-the-shoulder shot", "foreground shoulder framing"],
    "first_person": ["first-person POV", "point-of-view shot", "hands in foreground"],
    "third_person": ["third-person viewpoint", "camera behind subject"],
}
_ANGLE_NEGATIVE = [
    "impossible perspective",
    "warped viewpoint",
    "broken vanishing point",
]

_SEX_VIEW_POSITIVE: Dict[str, List[str]] = {
    "female": ["female anatomy consistency", "correct female body proportions"],
    "male": ["male anatomy consistency", "correct male body proportions"],
    "mixed": ["multiple subjects with distinct anatomy", "clear subject separation"],
    "nonbinary": ["androgynous presentation", "anatomical consistency"],
}

_DOMAIN_POSITIVE: Dict[str, List[str]] = {
    "objects": ["product-style object clarity", "distinct object edges", "material realism"],
    "vehicles": ["accurate vehicle geometry", "coherent wheel/body alignment", "automotive detail"],
    "buildings": ["architectural perspective", "straight structural lines", "facade detail"],
    "architecture": ["architectural composition", "building scale coherence", "clean geometry"],
    "mixed": ["multi-object scene coherence", "clear object hierarchy", "consistent perspective"],
}
_DOMAIN_NEGATIVE: Dict[str, List[str]] = {
    "objects": ["melted object", "fused object", "undefined object shape"],
    "vehicles": ["deformed wheels", "vehicle body distortion", "floating car parts"],
    "buildings": ["bent building lines", "impossible architecture", "warped windows"],
    "architecture": ["distorted perspective", "collapsed geometry", "warped straight lines"],
    "mixed": ["object merging", "foreground-background confusion", "scale mismatch"],
}

_BACKGROUND_POSITIVE: Dict[str, List[str]] = {
    "studio": ["studio backdrop", "controlled lighting", "clean background separation"],
    "indoor": ["coherent indoor environment", "interior depth cues", "room geometry consistency"],
    "outdoor": ["coherent outdoor environment", "natural atmospheric depth", "ground-plane consistency"],
    "urban": ["urban environment detail", "architectural perspective", "street-scale coherence"],
    "nature": ["natural landscape depth", "organic environment detail", "foliage separation"],
    "minimal": ["minimal background", "subject emphasis", "clean negative space"],
}
_BACKGROUND_NEGATIVE: Dict[str, List[str]] = {
    "studio": ["cluttered background", "background noise", "foreground bleed"],
    "indoor": ["impossible room geometry", "warped walls", "floating furniture"],
    "outdoor": ["flat backdrop", "collapsed depth", "incoherent horizon"],
    "urban": ["warped buildings", "broken vanishing point", "street distortion"],
    "nature": ["muddy foliage", "texture soup", "background collapse"],
    "minimal": ["busy background", "visual clutter"],
}

_PEOPLE_LAYOUT_POSITIVE: Dict[str, List[str]] = {
    "solo": ["single person", "one subject only", "clear subject focus"],
    "duo": ["two people", "distinct individuals", "clear separation between subjects"],
    "group_small": ["small group portrait", "distinct faces", "non-overlapping silhouettes"],
    "group_large": ["crowd scene", "layered subject depth", "clear foreground/background grouping"],
}
_PEOPLE_LAYOUT_NEGATIVE: Dict[str, List[str]] = {
    "solo": ["extra person", "background person", "duplicate body"],
    "duo": ["merged faces", "fused limbs", "third person artifact"],
    "group_small": ["face duplication", "subject fusion", "missing limbs"],
    "group_large": ["subject collapse", "crowd blur soup", "indistinct faces"],
}

_RELATIONSHIP_POSITIVE: Dict[str, List[str]] = {
    "neutral": ["neutral interpersonal spacing", "non-overlapping poses"],
    "romantic": ["romantic interaction", "gentle physical contact", "coherent paired pose"],
    "combat": ["combat choreography", "clear attacker-defender spacing", "dynamic tension"],
    "teamwork": ["cooperative group action", "shared focal objective", "coordinated pose direction"],
}
_RELATIONSHIP_NEGATIVE: Dict[str, List[str]] = {
    "neutral": ["awkward overlap", "merged bodies"],
    "romantic": ["anatomy merge", "fused torsos", "broken contact anatomy"],
    "combat": ["weapon clipping", "limb overlap confusion", "pose collision"],
    "teamwork": ["subject confusion", "unclear action hierarchy"],
}

_OBJECT_LAYOUT_POSITIVE: Dict[str, List[str]] = {
    "foreground_anchor": ["foreground anchor object", "clear object silhouette", "depth separation"],
    "rule_of_thirds": ["rule of thirds object placement", "balanced composition"],
    "symmetrical": ["symmetrical layout", "centered structural balance"],
    "asymmetrical": ["asymmetrical balance", "intentional visual weight distribution"],
}
_OBJECT_LAYOUT_NEGATIVE: Dict[str, List[str]] = {
    "foreground_anchor": ["object float", "object-background merge"],
    "rule_of_thirds": ["center lock artifact", "composition collapse"],
    "symmetrical": ["asymmetric distortion", "skewed central axis"],
    "asymmetrical": ["unbalanced clutter", "visual tangles"],
}

_HAND_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "stable": ["natural hands", "five fingers", "clear finger separation", "anatomically correct hands"],
    "detailed": ["detailed hands", "defined knuckles", "natural finger joints", "visible fingernails"],
    "grip": ["hands holding object", "physically plausible grip", "clear contact points"],
}
_HAND_NEGATIVE: Dict[str, List[str]] = {
    "stable": ["extra fingers", "missing fingers", "fused fingers", "broken hands"],
    "detailed": ["melted fingers", "deformed knuckles", "finger blobs"],
    "grip": ["floating hands", "object-hand clipping", "impossible grip"],
}

_POSE_NATURALNESS_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "natural": [
        "natural body posture",
        "realistic weight distribution",
        "anatomically plausible joint angles",
        "relaxed non-stiff pose",
    ],
    "dynamic_natural": [
        "dynamic but physically plausible pose",
        "grounded center of mass",
        "natural limb articulation",
        "motion with anatomical consistency",
    ],
    "intimate_natural": [
        "coherent interpersonal contact",
        "anatomically plausible paired pose",
        "natural torso and hip alignment",
        "balanced body overlap",
    ],
}
_POSE_NATURALNESS_NEGATIVE: Dict[str, List[str]] = {
    "natural": [
        "stiff pose",
        "mannequin posture",
        "unnatural joint bend",
        "broken body mechanics",
    ],
    "dynamic_natural": [
        "impossible action pose",
        "off-balance body",
        "dislocated limbs",
        "unnatural contortion",
    ],
    "intimate_natural": [
        "anatomy merge",
        "impossible body contact",
        "fused torsos",
        "broken paired pose geometry",
    ],
}

_TYPOGRAPHY_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "clean": ["clean typography", "legible lettering", "consistent kerning", "sharp text edges"],
    "poster": ["poster typography", "readable headline", "layout-aligned text blocks"],
    "ui": ["ui text clarity", "readable interface labels", "consistent icon-label spacing"],
}
_TYPOGRAPHY_NEGATIVE: Dict[str, List[str]] = {
    "clean": ["garbled text", "misspelled words", "warped letters", "illegible text"],
    "poster": ["broken headline", "incoherent text layout", "letter overlap artifacts"],
    "ui": ["ui gibberish text", "icon-text overlap", "misaligned labels"],
}

# One-shot scaffolding: first-try clarity, anatomy, and composition (stacks with safety_mode; deduped in CSV merge).
_ONE_SHOT_POSITIVE: List[str] = [
    "single subject focus",
    "clear hero subject",
    "coherent scene",
    "consistent lighting direction",
    "correct perspective",
    "sharp subject",
    "well framed",
    "complete anatomy in frame",
    "natural colors",
    "high clarity",
    "subject isolation",
    "clean silhouette",
    "obvious focal point",
]

_ONE_SHOT_NEGATIVE: List[str] = [
    "duplicate subject",
    "cloned face",
    "double head",
    "extra arms",
    "extra legs",
    "missing limbs",
    "bad hands",
    "mutated hands",
    "too many fingers",
    "fused fingers",
    "blurry",
    "out of focus subject",
    "muddy details",
    "jpeg artifacts",
    "worst quality",
    "low quality",
    "watermark",
    "cropped",
    "bad anatomy",
    "deformed",
    "disconnected limbs",
    "incoherent background",
    "inconsistent lighting",
    "visual clutter",
]

_QUALITY_PACK_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    # Same tokens as _BEST_MODEL_TAGS — use with safety_mode=none when you only want the quality ladder + detail pack.
    "top": list(_BEST_MODEL_TAGS),
    "one_shot": list(_ONE_SHOT_POSITIVE) + list(_BEST_MODEL_TAGS),
    "ultra_clean": ["ultra clean render", "high micro-contrast", "fine detail retention", "artifact-free finish"],
    "cinematic": ["cinematic grade", "filmic contrast", "controlled highlight rolloff", "depth-rich image"],
    "illustrative": ["clean stylized rendering", "shape readability", "crisp silhouette language"],
    "editorial": ["editorial photography look", "controlled dynamic range", "material fidelity"],
    # Fine texture / material readout (pairs well with editorial or photoreal prompts).
    "micro_detail": [
        "high frequency detail",
        "texture fidelity",
        "material read",
        "clean micro-contrast",
        "sharp fine structure",
    ],
}
_QUALITY_PACK_NEGATIVE: Dict[str, List[str]] = {
    "top": [
        "worst quality",
        "low quality",
        "jpeg artifacts",
        "blurry",
        "noise",
        "bad proportions",
        "watermark",
        "text overlay",
        "logo",
        "username",
        "signature",
        "bad hands",
        "extra digits",
        "mutated hands",
    ],
    "ultra_clean": ["jpeg artifacts", "macroblocking", "banding", "mushy details"],
    "cinematic": ["flat tonal range", "highlight clipping", "crushed shadows"],
    "illustrative": ["muddy line quality", "shape ambiguity", "texture soup"],
    "editorial": ["plastic skin", "overprocessed skin", "fake hdr look"],
    "one_shot": list(_ONE_SHOT_NEGATIVE)
    + [
        "bad proportions",
        "noise",
        "text overlay",
        "logo",
        "username",
        "signature",
        "extra digits",
    ],
}
_QUALITY_PACK_NEGATIVE["micro_detail"] = [
    "mushy texture",
    "lost fine detail",
    "plastic uniform surfaces",
    "waxy skin everywhere",
    "smeared micro-detail",
]

# Prompt adherence: reduce missing props, wrong outfit, and “prompt drift” on long captions.
_ADHERENCE_STANDARD_POSITIVE: List[str] = [
    "faithful to the prompt",
    "accurate to description",
    "all described elements present",
    "literal scene interpretation",
    "coherent with written details",
]
_ADHERENCE_STRICT_EXTRA_POSITIVE: List[str] = [
    "strict prompt adherence",
    "no invented objects beyond the description",
    "preserve every mentioned attribute",
    "exact outfit and props as described",
]
_ADHERENCE_STANDARD_NEGATIVE: List[str] = [
    "wrong subject",
    "missing key elements",
    "contradicts the description",
    "omitted props",
    "ignored clothing details",
    "wrong outfit",
    "wrong hair color",
    "prompt drift",
]
_ADHERENCE_STRICT_EXTRA_NEGATIVE: List[str] = [
    "hallucinated details",
    "extra subjects not in description",
    "merged conflicting concepts",
    "anachronistic props",
    "inconsistent character identity",
    "ignored foreground objects",
]

_ADHERENCE_PACK_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "standard": list(_ADHERENCE_STANDARD_POSITIVE),
    "strict": list(_ADHERENCE_STANDARD_POSITIVE) + list(_ADHERENCE_STRICT_EXTRA_POSITIVE),
}
_ADHERENCE_PACK_NEGATIVE: Dict[str, List[str]] = {
    "standard": list(_ADHERENCE_STANDARD_NEGATIVE),
    "strict": list(_ADHERENCE_STANDARD_NEGATIVE) + list(_ADHERENCE_STRICT_EXTRA_NEGATIVE),
}

_LIGHTING_MODE_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "natural_daylight": ["natural daylight", "soft global illumination", "plausible bounce light"],
    "studio_softbox": ["studio softbox lighting", "controlled key/fill ratio", "clean light wrap"],
    "dramatic_rim": ["dramatic rim light", "directional key light", "cinematic shadow sculpting"],
    "low_key": ["low-key lighting", "rich shadows", "controlled specular highlights"],
    "high_key": ["high-key lighting", "bright soft tonality", "low shadow harshness"],
}
_LIGHTING_MODE_NEGATIVE: Dict[str, List[str]] = {
    "natural_daylight": ["unnatural color cast", "inconsistent sun direction"],
    "studio_softbox": ["harsh mixed lighting", "uneven exposure patches"],
    "dramatic_rim": ["flat lighting", "unmotivated highlights"],
    "low_key": ["crushed blacks", "shadow noise blotches"],
    "high_key": ["blown highlights", "washed-out subject"],
}

_SKIN_DETAIL_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "natural_texture": ["natural skin texture", "real pores", "subtle imperfections", "non-waxy skin"],
    "clean_beauty": ["clean beauty skin", "balanced skin smoothing", "retained facial structure"],
    "stylized_skin": ["stylized skin rendering", "consistent skin shading language"],
}
_SKIN_DETAIL_NEGATIVE: Dict[str, List[str]] = {
    "natural_texture": ["waxy skin", "airbrushed plastic skin", "porcelain skin artifact"],
    "clean_beauty": ["over-smoothed skin", "loss of facial definition"],
    "stylized_skin": ["style-inconsistent skin", "skin shading collapse"],
}

_NSFW_PACK_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "soft": ["adult content", "anatomical coherence", "tasteful composition", "clear body readability", "subtle eroticism"],
    "explicit_detail": ["adult content", "high anatomy fidelity", "clear limb separation", "coherent contact geometry", "detailed skin texture", "realistic anatomy", "visible genital detail", "wet skin", "glistening fluids"],
    "romantic": ["adult romantic mood", "coherent paired pose", "natural interaction framing", "passionate eye contact", "tender yet intense"],
    "extreme": [
        "uncensored", "extreme detail", "explicit anatomy", "perfect proportions", "no censorship",
        "hyper detailed genitals", "visible penetration", "detailed pussy", "detailed cock", "veiny penis",
        "glistening wetness", "creamy fluids", "stringy saliva", "sweat droplets", "realistic arousal",
        "labia detail", "clitoral hood", "scrotum texture", "throbbing veins", "ejaculation physics",
        "puffy pussy", "swollen clit", "glans detail", "cum on tongue", "throat bulge", "belly bulge"
    ],
    "fluids": ["creamy pussy", "wet dripping", "cum overflow", "saliva trail", "sweaty bodies", "bodily fluids visible", "squirting", "creampie", "bukkake", "cum on face", "cum on tits", "cum dripping"],
    "amazon": ["onahole", "fleshlight", "automatic stroker", "suction cup dildo", "rabbit vibrator", "wand massager", "nipple clamps with chain", "ball gag with strap", "blindfold mask", "bondage rope", "spanking paddle", "latex catsuit", "pvc dress", "leather harness", "cage harness", "open cup bra", "crotchless panties", "realistic dildo", "anal beads", "strap on", "magic wand", "butt plug", "vibrator", "dildo", "nipple clamps"],
}

_NSFW_PACK_NEGATIVE: Dict[str, List[str]] = {
    "soft": ["broken anatomy", "merged limbs", "awkward overlap", "flat expression"],
    "explicit_detail": ["censorship bars", "mosaic censor", "fused torsos", "impossible contact geometry", "blurred private parts"],
    "romantic": ["stiff paired pose", "unnatural body contact", "emotionless expression"],
    "extreme": ["censorship bars", "mosaic censor", "deformed genitals", "impossible penetration geometry", "floating anatomy"],
    "fluids": ["dry skin", "no wetness", "missing fluid effects"],
    "amazon": ["broken toy geometry", "floating toy", "warped accessories"],
}

_SEX_POSITION_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "standing_missionary": ["standing missionary position", "deep penetration while standing", "legs wrapped around partner", "intense eye contact during sex"],
    "doggy": ["doggy style", "from behind deep penetration", "arched back", "hands gripping hips"],
    "cowgirl": ["cowgirl position", "woman on top riding", "straddling partner", "deep insertion"],
    "missionary": ["missionary position", "face to face deep penetration", "legs spread wide", "intimate connection"],
    "spooning": ["spooning sex position", "side by side penetration", "intimate rear entry"],
    "standing": ["standing sex", "lifted leg position", "wall pressed standing fuck"],
    "danbooru": ["prone bone", "mating press", "full nelson", "piledriver", "amazon position", "reverse cowgirl", "69", "face sitting", "lotus position", "butterfly position", "bridge position"],
}

_PENETRATION_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "normal": ["visible penetration", "deep insertion", "coherent genital contact"],
    "deep": ["very deep penetration", "cervix contact", "full insertion"],
    "extreme": ["impossibly deep penetration", "throat bulge from penetration", "long penis reaching mouth", "extreme anatomical distortion"],
}

_BODY_PROPORTION_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "realistic": ["realistic human proportions", "natural body ratios"],
    "exaggerated": ["exaggerated proportions", "hyper sexualized body", "extreme curves", "unrealistic penis size"],
    "hyper": ["hyper proportions", "massive penis", "impossibly long cock", "extreme body modification"],
}

_INTERACTION_INTENSITY: Dict[str, List[str]] = {
    "none": [],
    "gentle": ["gentle lovemaking", "tender interaction"],
    "passionate": ["passionate sex", "intense thrusting"],
    "intense": ["rough sex", "aggressive fucking", "powerful penetration"],
    "extreme": ["brutal sex", "violent thrusting", "maximum intensity"],
}

_CLOTHING_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "casual": ["casual outfit", "natural fabric folds", "realistic cloth drape", "detailed clothing texture"],
    "formal": ["formal outfit", "tailored clothing", "clean garment lines", "elegant dress"],
    "streetwear": ["streetwear style", "layered outfit", "distinct garment details", "urban fashion"],
    "fantasy_armor": ["fantasy armor", "readable armor segments", "material separation", "ornate armor details"],
    "swimwear": ["swimwear", "clean silhouette", "consistent fabric tension", "summer beachwear"],
    "lingerie": ["sexy lingerie", "lace lingerie", "sheer fabric", "garter belts", "stockings", "bodysuit", "teddy", "babydoll", "corset", "cage harness"],
    "torn": ["torn clothes", "ripped clothing", "clothes in tatters", "partially undressed", "naked apron"],
    "armor": ["fantasy armor", "revealing armor", "metal bikini armor", "leather straps", "bikini armor"],
    "nude": ["completely nude", "fully naked", "no clothing", "bare skin"],
    "bikini": ["micro bikini", "string bikini", "swimsuit pulled aside"],
    "danbooru": ["maid outfit", "school uniform", "thighhighs", "garter straps", "fishnets", "latex suit", "leather corset", "pasties", "crotchless panties", "microskirt", "sailor uniform", "cheerleader outfit", "gothic lolita", "nun habit", "shrine maiden", "bikini armor", "miko outfit", "succubus outfit", "demon outfit", "angel outfit", "witch hat and robe", "cat ears and tail", "bunny suit", "maid headdress"],
    "sfw": ["casual clothes", "elegant gown", "adventurer outfit", "cozy sweater", "historical dress", "sportswear", "royal attire", "fantasy robes", "simple tunic", "flowing dress", "hoodie and shorts", "summer dress", "winter coat", "apron dress", "pajamas", "uniform", "oversized sweater", "cardigan", "blouse and skirt", "sundress", "jeans and t-shirt", "cute dress", "kawaii outfit", "pastel clothes"],
}

_CLOTHING_NEGATIVE: Dict[str, List[str]] = {
    "none": [],
    "casual": ["melted clothing", "fused fabric", "broken seams", "floating clothes"],
    "formal": ["distorted suit", "warped tie", "asymmetric lapels"],
    "streetwear": ["muddy clothing details", "garment fusion", "texture collapse"],
    "fantasy_armor": ["merged armor plates", "floating armor parts", "warped metal"],
    "swimwear": ["broken straps", "warped swimsuit geometry"],
    "lingerie": ["broken lingerie straps", "warped lace", "plastic looking fabric"],
    "torn": ["badly torn clothes", "inconsistent damage"],
    "armor": ["merged armor plates", "floating armor parts"],
    "nude": ["deformed anatomy", "extra limbs", "broken joints"],
    "bikini": ["broken straps", "warped swimsuit geometry", "asymmetric cups"],
    "danbooru": ["melted costume", "fused fabric", "broken accessories"],
    "sfw": ["melted clothing", "fused fabric", "inconsistent outfit"],
}

_ADVANCED_POSE_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "dynamic": ["dynamic pose", "action pose", "motion blur on limbs", "weight shifted stance"],
    "erotic": ["seductive pose", "arched back", "legs spread", "hands running over body"],
    "struggle": ["struggling pose", "bound wrists", "resisting yet aroused"],
    "climax": ["orgasm pose", "body shaking", "toes curled", "back arched in pleasure"],
    "ahegao": ["ahegao face", "tongue out", "heart shaped pupils", "rolling eyes", "mind break", "pleasure overload"],
    "sfw": ["elegant pose", "graceful stance", "reading pose", "sitting peacefully", "walking gracefully", "dancing pose", "contemplative pose"],
}

_OBJECTS_INTERACTION_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "held": ["holding object", "physically plausible grip", "clear contact points"],
    "sex_toy": ["using sex toy", "dildo insertion", "vibrator on clit", "plug visible", "nipple clamps", "ball gag", "collar and leash", "riding crop"],
    "furniture": ["fucked on table", "bent over desk", "against wall", "on bed with sheets gripped"],
    "weapon": ["holding sword", "gun in hand", "sword at side", "weapon detail"],
    "danbooru": ["vibrator", "dildo", "anal plug", "handcuffs", "strap on", "wand vibrator", "anal beads", "tentacle", "magic wand", "book", "flower", "umbrella", "lantern", "basket", "tea cup"],
    "sfw": ["holding book", "playing instrument", "holding flower", "reading book", "painting", "gardening", "holding lantern"],
}

_ENVIRONMENT_DETAIL_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "bedroom": ["luxurious bedroom", "silk sheets", "dim romantic lighting", "candlelit room"],
    "dungeon": ["dark dungeon", "chains on wall", "stone floor", "bdsm dungeon"],
    "outdoor": ["forest clearing sex", "public risk", "against tree", "moonlit night"],
    "luxury": ["luxury hotel suite", "penthouse view", "marble floor"],
    "danbooru": ["bedroom", "bathroom", "classroom", "office", "forest", "beach", "alley", "rooftop", "throne room"],
    "sfw": ["cozy living room", "sunlit garden", "peaceful library", "art studio", "warm kitchen", "mountain cabin", "flower field"],
}

_STYLE_POSITIVE: Dict[str, List[str]] = {
    "3d": [
        "3d render",
        "cg render",
        "solid geometry",
        "consistent material shading",
        "octane-style lighting",
    ],
    "photoreal": [
        "photorealistic",
        "real-world textures",
        "natural skin/material detail",
        "camera-realistic lighting",
        "lens-consistent perspective",
    ],
    "semi_real": [
        "semi-realistic",
        "stylized realism",
        "balanced stylization and realism",
    ],
    "anime": [
        "anime style",
        "clean linework",
        "coherent cel-shading",
    ],
    "painterly": [
        "painterly style",
        "brushwork detail",
        "coherent painted textures",
    ],
    "3d_photoreal": [
        "photorealistic 3d render",
        "realistic cg materials",
        "cinematic physically based lighting",
    ],
}
_STYLE_NEGATIVE: Dict[str, List[str]] = {
    "3d": ["flat 2d look", "painted texture smear", "broken geometry", "plastic artifacting"],
    "photoreal": ["cartoon look", "anime lineart", "cgi plastic skin", "painterly brush strokes"],
    "semi_real": ["style collapse", "over-cartooned", "over-photographic mismatch"],
    "anime": ["photographic pores", "uncanny realism", "muddy linework"],
    "painterly": ["photo artifacts", "over-sharp photographic texture", "style inconsistency"],
    "3d_photoreal": ["toy-like plastic look", "flat shading", "non-physical reflections"],
}

_STYLE_LOCK_POSITIVE = [
    "style consistency",
    "single coherent art direction",
    "uniform rendering style",
]
_STYLE_LOCK_NEGATIVE = [
    "style bleed",
    "mixed incompatible styles",
    "style drift",
    "visual style inconsistency",
]

_UNWANTED_TEXT_NEGATIVE = [
    "watermark",
    "logo",
    "signature",
    "brand mark",
    "caption overlay",
    "subtitle overlay",
    "random text",
    "letters",
    "numbers",
    "typography",
]

_COMPOSITION_POSITIVE: Dict[str, List[str]] = {
    "single_subject": ["single subject focus", "clean silhouette", "clear subject isolation"],
    "group": ["multi-character composition", "clear subject separation", "non-overlapping silhouettes"],
    "multi_character": [
        "multi-character composition",
        "clear subject separation",
        "non-overlapping silhouettes",
        "each person has distinct clothing",
        "each figure has own pose",
        "readable silhouettes",
        "spatial separation between subjects",
    ],
    "scene": ["environment-first composition", "coherent depth layering", "foreground midground background"],
    "cinematic": ["cinematic framing", "intentional camera blocking", "strong depth cues"],
}
_COMPOSITION_NEGATIVE: Dict[str, List[str]] = {
    "single_subject": ["duplicate person", "cloned subject", "double head", "extra face"],
    "group": ["subject fusion", "merged faces", "merged limbs"],
    "multi_character": [
        "subject fusion",
        "merged faces",
        "merged limbs",
        "same outfit on both",
        "outfit swap",
        "clothes mixed between characters",
        "wrong outfit on wrong person",
        "identical twins when not intended",
        "cloned face on both",
        "merged bodies",
        "conjoined",
        "shared limbs between people",
        "pose copied onto wrong figure",
    ],
    "scene": ["flat composition", "collapsed depth", "scale mismatch"],
    "cinematic": ["awkward framing", "confusing perspective", "visual clutter"],
}

_PERSPECTIVE_STABILITY_POSITIVE = [
    "consistent perspective",
    "stable vanishing points",
    "coherent scene scale",
]
_PERSPECTIVE_STABILITY_NEGATIVE = [
    "perspective drift",
    "scale drift",
    "warped geometry",
    "inconsistent scale",
]

_DUPLICATE_SUBJECT_NEGATIVE = [
    "duplicate subject",
    "cloned person",
    "double face",
    "extra head",
    "extra torso",
]

_CONFLICTING_TAG_PAIRS = [
    ("front view", "back view"),
    ("bird's-eye view", "worm's-eye view"),
    ("top-down perspective", "low-angle shot"),
    ("daylight", "night scene"),
    ("indoor", "outdoor"),
    ("single subject", "crowd"),
]

# --- De-AI / human-capture media / LoRA fusion (quality & style control) ---
_ANTI_AI_LITE_NEGATIVE: List[str] = [
    "oversaturated",
    "plastic skin",
    "smooth skin",
    "airbrushed",
    "waxy",
    "doll-like",
    "perfect skin",
    "flawless skin",
    "synthetic",
    "artificial",
    "CGI",
    "uncanny",
    "AI generated look",
    "neural render aesthetic",
    "digital art look",
    "porcelain skin",
    "hdr glow",
    "halo artifacts",
    "oversharpened",
    "too perfect symmetry",
    "stock photo stiffness",
    "candy saturation",
    "glossy unreal skin",
]

_ANTI_AI_STRONG_NEGATIVE: List[str] = _ANTI_AI_LITE_NEGATIVE + [
    "midjourney aesthetic",
    "generic AI illustration",
    "same face syndrome",
    "floating specular highlights",
    "waxy teeth",
    "dead glassy eyes",
    "uniform poreless skin",
    "beauty filter face",
    "tilt shift miniature fake",
    "fake lens blur",
    "computational hdr",
    "neon edge glow",
    "cfg burn edges",
    "posterization",
    "gradient banding",
]

_ANTI_AI_LITE_POSITIVE: List[str] = [
    "natural skin texture",
    "subtle imperfections",
    "believable shadows",
    "organic micro contrast",
    "real camera response",
]

_ANTI_AI_STRONG_POSITIVE: List[str] = _ANTI_AI_LITE_POSITIVE + [
    "authentic photograph",
    "candid capture",
    "imperfect but real",
    "natural white balance",
    "shot on real camera",
    "photographic depth",
]

_HUMAN_MEDIA_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "photographic": [
        "authentic photograph",
        "believable exposure",
        "natural dynamic range",
        "real world texture",
        "photographic composition",
        "captured image not rendered",
    ],
    "dslr": [
        "dslr photograph",
        "full frame look",
        "natural lens bokeh",
        "pleasant optical vignette",
        "sharp subject natural falloff",
        "real lens character",
    ],
    "film": [
        "35mm film photograph",
        "analog film grain",
        "film color science",
        "subtle halation",
        "organic grain structure",
        "portra palette subtle",
    ],
}

_HUMAN_MEDIA_NEGATIVE: Dict[str, List[str]] = {
    "photographic": [
        "cg render",
        "game engine screenshot",
        "3d model turntable",
        "fake hdr",
    ],
    "dslr": [
        "phone computational mush",
        "over processed smartphone hdr",
    ],
    "film": [
        "digital noise pattern",
        "sensor banding as grain",
    ],
}

_LORA_SCAFFOLD_POSITIVE: Dict[str, List[str]] = {
    "none": [],
    "blend": [
        "coherent lora fusion",
        "unified adaptation",
        "single harmonized style",
        "consistent trigger strength feel",
    ],
    "character_first": [
        "locked character design",
        "consistent facial structure",
        "same outfit logic",
        "character model consistency",
    ],
    "style_first": [
        "dominant lora style",
        "style transfer coherence",
        "clear art direction from trigger",
    ],
}

_LORA_SCAFFOLD_NEGATIVE: Dict[str, List[str]] = {
    "blend": [
        "double adaptation clash",
        "split style artifact",
        "muddy lora blend",
        "ghosting from stacked loras",
    ],
    "character_first": [
        "character face drift",
        "morphing identity",
        "inconsistent character",
    ],
    "style_first": [
        "weak style adherence",
        "washed lora effect",
        "conflicting style cues",
    ],
}


def _split_csv_tokens(text: str) -> List[str]:
    return [t.strip() for t in (text or "").split(",") if t.strip()]


def _append_unique_csv(base_text: str, additions: Sequence[str]) -> str:
    base = _split_csv_tokens(base_text)
    seen = {t.lower() for t in base}
    out = list(base)
    for token in additions:
        t = token.strip()
        if not t:
            continue
        key = t.lower()
        if key not in seen:
            seen.add(key)
            out.append(t)
    return ", ".join(out)


def _remove_conflicting_tags(text: str) -> str:
    """
    Remove obvious contradictory tag pairs by keeping the first occurrence in-order.
    """
    tokens = _split_csv_tokens(text)
    if not tokens:
        return text
    lowered = [t.lower() for t in tokens]
    to_remove = set()
    for a, b in _CONFLICTING_TAG_PAIRS:
        a_idx = next((i for i, t in enumerate(lowered) if a in t), None)
        b_idx = next((i for i, t in enumerate(lowered) if b in t), None)
        if a_idx is None or b_idx is None:
            continue
        if a_idx < b_idx:
            to_remove.add(b_idx)
        else:
            to_remove.add(a_idx)
    cleaned = [t for i, t in enumerate(tokens) if i not in to_remove]
    return ", ".join(cleaned)


def infer_content_controls_from_prompt(prompt: str) -> Dict[str, str]:
    """
    Infer likely control modes from prompt keywords.
    Returns partial kwargs for `apply_content_controls`.
    """
    p = (prompt or "").lower()
    out: Dict[str, str] = {}

    if any(k in p for k in ["car", "vehicle", "truck", "motorcycle", "bicycle", "bus"]):
        out["scene_domain"] = "vehicles"
    elif any(k in p for k in ["building", "architecture", "facade", "skyscraper", "interior"]):
        out["scene_domain"] = "architecture"
    elif any(k in p for k in ["object", "product shot", "tabletop", "still life"]):
        out["scene_domain"] = "objects"

    if any(k in p for k in ["first person", "pov", "through the eyes"]):
        out["view_angle"] = "first_person"
    elif any(k in p for k in ["bird eye", "bird's-eye", "overhead", "top down"]):
        out["view_angle"] = "bird_eye"
    elif any(k in p for k in ["low angle", "from below", "worm eye", "worm's-eye"]):
        out["view_angle"] = "low_angle"

    if any(k in p for k in ["action pose", "acrobat", "parkour", "jumping", "spinning kick"]):
        out["pose_mode"] = "action"

    # NSFW vs SFW (NSFW wins on conflict)
    _nsfw_triggers = (
        "nsfw",
        "nude",
        "naked",
        "explicit",
        "adult content",
        "erotic",
        "uncensored",
        "porn",
        "hentai",
        "fucking",
        "fuck ",
        " sex ",
        "sex,",
        "sexual",
        "penetration",
        "ahegao",
        "creampie",
        "blowjob",
        "oral sex",
        " anal ",
        "vaginal",
        "dildo",
        "vibrator",
        "bukkake",
        "cum ",
        "cumming",
        "orgasm",
        "masturbat",
        "thighjob",
        "paizuri",
        "footjob",
        "spread legs",
        "doggy style",
        "missionary",
        "cowgirl",
        "reverse cowgirl",
        "69",
        "nipples",
        "areola",
        "pussy",
        "penis",
        "cock ",
        "dick ",
        "cumshot",
        "facial cum",
    )
    nsfw_hit = any(k in p for k in _nsfw_triggers)
    if nsfw_hit:
        out["safety_mode"] = "nsfw"
        if any(k in p for k in ["extreme", "macro", "throat bulge", "ahegao", "mind break", "brutal"]):
            out["nsfw_pack"] = "extreme"
        elif any(k in p for k in ["romantic", "gentle", "tender", "couple", "cuddling"]):
            out["nsfw_pack"] = "romantic"
        elif any(k in p for k in ["detailed", "closeup", "macro", "hi res", "highres"]):
            out["nsfw_pack"] = "explicit_detail"
        if "doggy" in p or "from behind" in p or "prone bone" in p:
            out["sex_position"] = "doggy"
        elif "reverse cowgirl" in p:
            out["sex_position"] = "cowgirl"
        elif "cowgirl" in p:
            out["sex_position"] = "cowgirl"
        elif "missionary" in p:
            out["sex_position"] = "missionary"
        elif "spoon" in p:
            out["sex_position"] = "spooning"
        elif "standing" in p and any(k in p for k in ["sex", "fuck", "penetration"]):
            out["sex_position"] = "standing"
        if "lingerie" in p:
            out["clothing_mode"] = "lingerie"
        elif "bikini" in p:
            out["clothing_mode"] = "bikini"
        elif "torn" in p or "ripped clothes" in p:
            out["clothing_mode"] = "torn"
    else:
        _sfw_triggers = (
            "sfw,",
            "sfw ",
            "safe for work",
            "family friendly",
            "pg-13",
            "pg rated",
            "wholesome only",
            "linkedin headshot",
            "corporate headshot",
            "christmas card",
            "school photo",
            "wedding photo",
            "toddler portrait",
        )
        if any(t in p for t in _sfw_triggers):
            out["safety_mode"] = "sfw"

    # Solo / duo composition (Danbooru-style counts)
    if (
        any(x in p for x in ["1girl", "1boy", "1other", "single girl", "single boy", "solo"])
        and not any(x in p for x in ["2girls", "2boys", "3girls", "group", "crowd", "orgy"])
    ):
        out["composition_mode"] = "single_subject"
        out["people_layout"] = "solo"
    elif any(x in p for x in ["2girls", "2boys", "couple", "two girls", "two boys", "two people", "duo"]):
        out["people_layout"] = "duo"
        if out.get("composition_mode") in (None, "none"):
            out["composition_mode"] = "multi_character"

    if any(x in p for x in ["hand focus", "holding hands", "hands visible", "detailed hands", "fingers"]):
        out["hand_mode"] = "stable"

    if "golden hour" in p or "sunset" in p or "sunrise" in p:
        out["lighting_mode"] = "dramatic_rim"
    elif "studio lighting" in p or "white background" in p or "simple background" in p:
        out["lighting_mode"] = "studio_softbox"
    elif "overcast" in p or "cloudy day" in p or "soft daylight" in p:
        out["lighting_mode"] = "natural_daylight"

    # Style inference for difficult style adherence
    if any(k in p for k in ["3d render", "cg", "octane", "blender render", "unreal engine"]):
        out["style_mode"] = "3d"
    elif any(k in p for k in ["photoreal", "raw photo", "dslr", "real photograph"]):
        out["style_mode"] = "photoreal"
    elif any(k in p for k in ["semi realistic", "semi-realistic", "stylized realism", "2.5d"]):
        out["style_mode"] = "semi_real"
    elif any(k in p for k in ["anime", "manga style", "cel shading", "visual novel"]):
        out["style_mode"] = "anime"

    # Human-capture media (de-CGI) — only when not already set by caller
    if any(
        k in p
        for k in [
            "35mm",
            "kodak",
            "portra",
            "fuji film",
            "film photograph",
            "analog photo",
            "cinestill",
        ]
    ):
        out["human_media_mode"] = "film"
    elif any(
        k in p
        for k in [
            "dslr",
            "shot on canon",
            "shot on nikon",
            "shot on sony",
            "85mm",
            "50mm lens",
            "full frame",
        ]
    ):
        out["human_media_mode"] = "dslr"
    elif any(
        k in p
        for k in [
            "photorealistic",
            "raw photo",
            "real photograph",
            "realistic photo",
            "iphone photo",
            "smartphone photo realistic",
        ]
    ):
        out["human_media_mode"] = "photographic"

    # Long / detailed prompts benefit from explicit adherence scaffolding (upgrade with keywords).
    raw_prompt = (prompt or "").strip()
    parts = [x.strip() for x in raw_prompt.split(",") if x.strip()]
    n_parts = len(parts)
    plen = len(raw_prompt)
    inferred_adherence = "none"
    if n_parts >= 12 or plen >= 280:
        inferred_adherence = "standard"
    if n_parts >= 22 or plen >= 520:
        inferred_adherence = "strict"
    if any(
        k in p
        for k in [
            "as described",
            "faithful to prompt",
            "accurate to description",
            "per the prompt",
            "match the caption",
            "follow the prompt",
        ]
    ):
        inferred_adherence = "standard" if inferred_adherence == "none" else inferred_adherence
    if any(
        k in p
        for k in [
            "strict adherence",
            "exactly as described",
            "match every detail",
            "no extra elements",
            "no additions beyond",
        ]
    ):
        inferred_adherence = "strict"
    if inferred_adherence != "none":
        out["adherence_pack"] = inferred_adherence

    return out


def apply_content_controls(
    prompt: str,
    negative_prompt: str,
    *,
    safety_mode: str = "none",
    pose_mode: str = "none",
    view_angle: str = "none",
    subject_sex: str = "none",
    scene_domain: str = "none",
    clothing_mode: str = "none",
    background_mode: str = "none",
    people_layout: str = "none",
    relationship_mode: str = "none",
    object_layout: str = "none",
    hand_mode: str = "none",
    pose_naturalness: str = "none",
    typography_mode: str = "none",
    quality_pack: str = "none",
    lighting_mode: str = "none",
    skin_detail_mode: str = "none",
    nsfw_pack: str = "none",
    sex_position: str = "none",
    penetration_detail: str = "none",
    body_proportion: str = "none",
    interaction_intensity: str = "none",
    advanced_pose: str = "none",
    object_interaction: str = "none",
    environment_type: str = "none",
    sfw_mood: str = "none",
    sfw_pose: str = "none",
    sfw_clothing: str = "none",
    sfw_environment: str = "none",
    sfw_expression: str = "none",
    style_mode: str = "none",
    style_lock: bool = False,
    anti_style_bleed: bool = False,
    composition_mode: str = "none",
    anti_duplicate_subjects: bool = False,
    anti_perspective_drift: bool = False,
    cleanup_conflicting_tags: bool = False,
    allow_text_in_image: bool = False,
    nsfw_civitai_pack: str = "none",
    civitai_trigger_bank: str = "none",
    civitai_model_bank_csv: Optional[str] = None,
    civitai_frequency_txt: Optional[str] = None,
    one_shot_boost: bool = False,
    anti_ai_pack: str = "none",
    human_media_mode: str = "none",
    lora_scaffold: str = "none",
    adherence_pack: str = "none",
) -> Tuple[str, str]:
    """
    Apply optional content controls to prompt + negative prompt.

    Returns `(updated_prompt, updated_negative_prompt)`.
    """
    p = (prompt or "").strip()
    n = (negative_prompt or "").strip()

    if safety_mode == "sfw":
        p = _append_unique_csv(p, _SFW_POSITIVE)
        n = _append_unique_csv(n, _SFW_NEGATIVE)
    elif safety_mode == "nsfw":
        p = _append_unique_csv(p, _NSFW_POSITIVE)
        n = _append_unique_csv(n, _NSFW_NEGATIVE)

    if one_shot_boost:
        p = _append_unique_csv(p, _ONE_SHOT_POSITIVE)
        n = _append_unique_csv(n, _ONE_SHOT_NEGATIVE)

    # New SFW controls
    if sfw_mood in _SFW_MOOD_POSITIVE:
        p = _append_unique_csv(p, _SFW_MOOD_POSITIVE[sfw_mood])
    if sfw_pose in _SFW_POSE_POSITIVE:
        p = _append_unique_csv(p, _SFW_POSE_POSITIVE[sfw_pose])
    if sfw_clothing in _SFW_CLOTHING_POSITIVE:
        p = _append_unique_csv(p, _SFW_CLOTHING_POSITIVE[sfw_clothing])
    if sfw_environment in _SFW_ENVIRONMENT_POSITIVE:
        p = _append_unique_csv(p, _SFW_ENVIRONMENT_POSITIVE[sfw_environment])
    if sfw_expression in _SFW_EXPRESSION_POSITIVE:
        p = _append_unique_csv(p, _SFW_EXPRESSION_POSITIVE[sfw_expression])

    if pose_mode in _POSE_POSITIVE:
        p = _append_unique_csv(p, _POSE_POSITIVE[pose_mode])
        n = _append_unique_csv(n, _POSE_NEGATIVE)

    if view_angle in _ANGLE_POSITIVE:
        p = _append_unique_csv(p, _ANGLE_POSITIVE[view_angle])
        n = _append_unique_csv(n, _ANGLE_NEGATIVE)

    if subject_sex in _SEX_VIEW_POSITIVE:
        p = _append_unique_csv(p, _SEX_VIEW_POSITIVE[subject_sex])

    if scene_domain in _DOMAIN_POSITIVE:
        p = _append_unique_csv(p, _DOMAIN_POSITIVE[scene_domain])
        n = _append_unique_csv(n, _DOMAIN_NEGATIVE.get(scene_domain, []))

    if clothing_mode in _CLOTHING_POSITIVE:
        p = _append_unique_csv(p, _CLOTHING_POSITIVE[clothing_mode])
        n = _append_unique_csv(n, _CLOTHING_NEGATIVE.get(clothing_mode, []))

    if background_mode in _BACKGROUND_POSITIVE:
        p = _append_unique_csv(p, _BACKGROUND_POSITIVE[background_mode])
        n = _append_unique_csv(n, _BACKGROUND_NEGATIVE.get(background_mode, []))

    if people_layout in _PEOPLE_LAYOUT_POSITIVE:
        p = _append_unique_csv(p, _PEOPLE_LAYOUT_POSITIVE[people_layout])
        n = _append_unique_csv(n, _PEOPLE_LAYOUT_NEGATIVE.get(people_layout, []))

    if relationship_mode in _RELATIONSHIP_POSITIVE:
        p = _append_unique_csv(p, _RELATIONSHIP_POSITIVE[relationship_mode])
        n = _append_unique_csv(n, _RELATIONSHIP_NEGATIVE.get(relationship_mode, []))

    if object_layout in _OBJECT_LAYOUT_POSITIVE:
        p = _append_unique_csv(p, _OBJECT_LAYOUT_POSITIVE[object_layout])
        n = _append_unique_csv(n, _OBJECT_LAYOUT_NEGATIVE.get(object_layout, []))

    if hand_mode in _HAND_POSITIVE:
        p = _append_unique_csv(p, _HAND_POSITIVE[hand_mode])
        n = _append_unique_csv(n, _HAND_NEGATIVE.get(hand_mode, []))

    if pose_naturalness in _POSE_NATURALNESS_POSITIVE:
        p = _append_unique_csv(p, _POSE_NATURALNESS_POSITIVE[pose_naturalness])
        n = _append_unique_csv(n, _POSE_NATURALNESS_NEGATIVE.get(pose_naturalness, []))

    if typography_mode in _TYPOGRAPHY_POSITIVE:
        p = _append_unique_csv(p, _TYPOGRAPHY_POSITIVE[typography_mode])
        n = _append_unique_csv(n, _TYPOGRAPHY_NEGATIVE.get(typography_mode, []))

    if quality_pack in _QUALITY_PACK_POSITIVE:
        p = _append_unique_csv(p, _QUALITY_PACK_POSITIVE[quality_pack])
        n = _append_unique_csv(n, _QUALITY_PACK_NEGATIVE.get(quality_pack, []))

    if adherence_pack in _ADHERENCE_PACK_POSITIVE:
        p = _append_unique_csv(p, _ADHERENCE_PACK_POSITIVE[adherence_pack])
        n = _append_unique_csv(n, _ADHERENCE_PACK_NEGATIVE.get(adherence_pack, []))

    if lighting_mode in _LIGHTING_MODE_POSITIVE:
        p = _append_unique_csv(p, _LIGHTING_MODE_POSITIVE[lighting_mode])
        n = _append_unique_csv(n, _LIGHTING_MODE_NEGATIVE.get(lighting_mode, []))

    if skin_detail_mode in _SKIN_DETAIL_POSITIVE:
        p = _append_unique_csv(p, _SKIN_DETAIL_POSITIVE[skin_detail_mode])
        n = _append_unique_csv(n, _SKIN_DETAIL_NEGATIVE.get(skin_detail_mode, []))

    if nsfw_pack in _NSFW_PACK_POSITIVE:
        p = _append_unique_csv(p, _NSFW_PACK_POSITIVE[nsfw_pack])
        n = _append_unique_csv(n, _NSFW_PACK_NEGATIVE.get(nsfw_pack, []))

    if safety_mode == "nsfw" and nsfw_civitai_pack in _NSFW_CIVITAI_POSITIVE:
        p = _append_unique_csv(p, _NSFW_CIVITAI_POSITIVE[nsfw_civitai_pack])
        n = _append_unique_csv(n, _NSFW_CIVITAI_NEGATIVE.get(nsfw_civitai_pack, []))

    if safety_mode == "nsfw" and civitai_trigger_bank in _CIVITAI_TRIGGER_BANK_CAPS:
        cap = _CIVITAI_TRIGGER_BANK_CAPS[civitai_trigger_bank]
        if cap > 0:
            if civitai_trigger_bank.startswith("frequency_"):
                ft = (civitai_frequency_txt or "").strip()
                freq_path: Optional[Path] = Path(ft) if ft else None
                triggers = load_civitai_frequency_triggers(freq_path, max_tokens=cap)
            else:
                csv_opt = (civitai_model_bank_csv or "").strip()
                bank_path: Optional[Path] = Path(csv_opt) if csv_opt else None
                triggers = load_civitai_model_bank_triggers(bank_path, max_tokens=cap)
            if triggers:
                p = _append_unique_csv(p, triggers)

    if sex_position in _SEX_POSITION_POSITIVE:
        p = _append_unique_csv(p, _SEX_POSITION_POSITIVE[sex_position])

    if penetration_detail in _PENETRATION_POSITIVE:
        p = _append_unique_csv(p, _PENETRATION_POSITIVE[penetration_detail])

    if body_proportion in _BODY_PROPORTION_POSITIVE:
        p = _append_unique_csv(p, _BODY_PROPORTION_POSITIVE[body_proportion])

    if interaction_intensity in _INTERACTION_INTENSITY:
        p = _append_unique_csv(p, _INTERACTION_INTENSITY[interaction_intensity])

    if advanced_pose in _ADVANCED_POSE_POSITIVE:
        p = _append_unique_csv(p, _ADVANCED_POSE_POSITIVE[advanced_pose])

    if object_interaction in _OBJECTS_INTERACTION_POSITIVE:
        p = _append_unique_csv(p, _OBJECTS_INTERACTION_POSITIVE[object_interaction])

    if environment_type in _ENVIRONMENT_DETAIL_POSITIVE:
        p = _append_unique_csv(p, _ENVIRONMENT_DETAIL_POSITIVE[environment_type])

    if style_mode in _STYLE_POSITIVE:
        p = _append_unique_csv(p, _STYLE_POSITIVE[style_mode])
        n = _append_unique_csv(n, _STYLE_NEGATIVE.get(style_mode, []))

    if style_lock:
        p = _append_unique_csv(p, _STYLE_LOCK_POSITIVE)
        n = _append_unique_csv(n, _STYLE_LOCK_NEGATIVE)
    elif anti_style_bleed:
        n = _append_unique_csv(n, _STYLE_LOCK_NEGATIVE)

    if composition_mode in _COMPOSITION_POSITIVE:
        p = _append_unique_csv(p, _COMPOSITION_POSITIVE[composition_mode])
        n = _append_unique_csv(n, _COMPOSITION_NEGATIVE.get(composition_mode, []))

    if anti_duplicate_subjects:
        n = _append_unique_csv(n, _DUPLICATE_SUBJECT_NEGATIVE)

    if anti_perspective_drift:
        p = _append_unique_csv(p, _PERSPECTIVE_STABILITY_POSITIVE)
        n = _append_unique_csv(n, _PERSPECTIVE_STABILITY_NEGATIVE)

    if anti_ai_pack == "lite":
        p = _append_unique_csv(p, _ANTI_AI_LITE_POSITIVE)
        n = _append_unique_csv(n, _ANTI_AI_LITE_NEGATIVE)
    elif anti_ai_pack == "strong":
        p = _append_unique_csv(p, _ANTI_AI_STRONG_POSITIVE)
        n = _append_unique_csv(n, _ANTI_AI_STRONG_NEGATIVE)

    if human_media_mode in _HUMAN_MEDIA_POSITIVE and human_media_mode != "none":
        p = _append_unique_csv(p, _HUMAN_MEDIA_POSITIVE[human_media_mode])
        n = _append_unique_csv(n, _HUMAN_MEDIA_NEGATIVE.get(human_media_mode, []))

    if lora_scaffold in _LORA_SCAFFOLD_POSITIVE and lora_scaffold != "none":
        p = _append_unique_csv(p, _LORA_SCAFFOLD_POSITIVE[lora_scaffold])
        n = _append_unique_csv(n, _LORA_SCAFFOLD_NEGATIVE.get(lora_scaffold, []))

    if not allow_text_in_image:
        n = _append_unique_csv(n, _UNWANTED_TEXT_NEGATIVE)

    if cleanup_conflicting_tags:
        p = _remove_conflicting_tags(p)

    return p, n
