"""
Research-backed idea catalog for frontier experiments.

Each entry links to a paper/project and notes implementation status in SDX.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal

Status = Literal["implemented", "partial", "planned", "research"]


@dataclass(frozen=True)
class ResearchIdea:
    id: str
    title: str
    source: str
    url: str
    status: Status
    module: str
    summary: str


IDEAS: List[ResearchIdea] = [
    ResearchIdea(
        id="regional_cfg",
        title="Training-free regional prompting (DiT)",
        source="Regional-Prompting-FLUX / InstantX",
        url="https://arxiv.org/html/2411.02395",
        status="implemented",
        module="utils/generation/regional_box_prompting.py",
        summary="Per-box prompts + masks blended during CFG; mask_inject_steps + base_ratio.",
    ),
    ResearchIdea(
        id="box_sketch",
        title="Draw + describe per region",
        source="Ideogram / sketch-conditioned layout",
        url="https://ideogram.ai",
        status="implemented",
        module="utils/generation/regional_box_sketch.py",
        summary="Vector strokes or sketch PNG per box with text prompt.",
    ),
    ResearchIdea(
        id="omost_canvas",
        title="Omost Canvas → layout DSL",
        source="lllyasviel/Omost",
        url="https://github.com/lllyasviel/Omost",
        status="implemented",
        module="frontier/layout/omost_canvas.py",
        summary="LLM-friendly Canvas API compiles to box-layout JSON.",
    ),
    ResearchIdea(
        id="consist_compose",
        title="Coordinate-bound prompts (LELG)",
        source="ConsistCompose CVPR 2026",
        url="https://openaccess.thecvf.com/content/CVPR2026/html/Shi_ConsistCompose_Unified_Multimodal_Layout_Control_for_Image_Composition_CVPR_2026_paper.html",
        status="implemented",
        module="frontier/layout/coordinate_bind.py",
        summary="Embed bbox tokens in prompts for coordinate-aware CFG.",
    ),
    ResearchIdea(
        id="lamic_schedule",
        title="LAMIC region-modulated fusion schedule",
        source="LAMIC AAAI 2026",
        url="https://arxiv.org/html/2508.00477",
        status="implemented",
        module="frontier/layout/lamic_schedule.py",
        summary="Early-step region isolation, late-step cross-region fusion.",
    ),
    ResearchIdea(
        id="lamic_metrics",
        title="Layout metrics IN-R / FI-R / BG-S",
        source="LAMIC AAAI 2026",
        url="https://ojs.aaai.org/index.php/AAAI/article/view/37311",
        status="implemented",
        module="frontier/layout/layout_metrics.py",
        summary="Inclusion and fill ratios for box-layout QA.",
    ),
    ResearchIdea(
        id="dynamic_cfg",
        title="Dynamic CFG via latent feedback",
        source="Google Imagen 3 research",
        url="https://arxiv.org/html/2509.16131",
        status="implemented",
        module="frontier/guidance/dynamic_cfg.py",
        summary="Greedy per-step CFG pick from cheap latent heuristics.",
    ),
    ResearchIdea(
        id="cfg_interval",
        title="CFG guidance intervals",
        source="Kynkäänniemi et al. / CFG scheduler analysis",
        url="https://ar5iv.labs.arxiv.org/html/2404.13040",
        status="implemented",
        module="frontier/guidance/guidance_interval.py",
        summary="Skip CFG early/late; monotonic cosine ramp mid-schedule.",
    ),
    ResearchIdea(
        id="cross_attn_layout",
        title="Cross-attention layout guidance",
        source="BoxDiff / Attend-and-Excite / Dense Diffusion",
        url="https://arxiv.org/html/2304.03373",
        status="partial",
        module="frontier/attention/layout_plan.py",
        summary="Training-free plan: which steps to enforce box attention (hook point).",
    ),
    ResearchIdea(
        id="multi_ref_region",
        title="Per-region identity / reference image",
        source="Regional-Prompting-FLUX + PULID",
        url="https://github.com/instantX-research/Regional-Prompting-FLUX",
        status="implemented",
        module="frontier/compose/multi_reference.py",
        summary="Attach reference image per box for identity-locked regions.",
    ),
    ResearchIdea(
        id="metapoint",
        title="MetaPoint spatial tokens",
        source="MetaPoint 2026",
        url="https://arxiv.org/html/2606.05031",
        status="planned",
        module="frontier/layout/",
        summary="Coordinate tokens for move/add/remove/edit — needs DiT token hook.",
    ),
    ResearchIdea(
        id="dense_diffusion",
        title="Dense Diffusion attention masking",
        source="Naver Dense Diffusion",
        url="https://github.com/naver-ai/DenseDiffusion",
        status="planned",
        module="models/",
        summary="Modify q@k scores per region inside cross-attn blocks.",
    ),
    ResearchIdea(
        id="cads",
        title="CADS condition annealing",
        source="CADS / holy grail",
        url="https://github.com/huggingface/diffusers",
        status="partial",
        module="diffusion/sampling/",
        summary="Already in sampling helpers; extend to per-region condition noise.",
    ),
    ResearchIdea(
        id="self_refine_loop",
        title="Generate → VLM critique → re-prompt",
        source="Agentic T2I 2025–2026",
        url="https://arxiv.org/html/2606.05031",
        status="partial",
        module="innovations/agentic/",
        summary="Wire frontier layout metrics into iterative refinement loop.",
    ),
    # --- Horizon: ahead-of-curve (2026) ---
    ResearchIdea(
        id="physical_plausibility",
        title="Cause-effect plausibility scan",
        source="World-model / physics-aware T2I trend",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/causality/physical_plausibility.py",
        summary="Flag missing implied effects (rain→wet) before sampling.",
    ),
    ResearchIdea(
        id="compute_budget",
        title="Adaptive guidance compute tiers",
        source="Product + TeaCache / step-skip literature",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/economy/compute_budget.py",
        summary="SKIP/LITE/FULL/HEAVY tiers per denoise step.",
    ),
    ResearchIdea(
        id="world_bible",
        title="Persistent world / character bible",
        source="Character-consistent series generation",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/world/world_bible.py",
        summary="JSON world state with locks, refs, and carry-over prompts.",
    ),
    ResearchIdea(
        id="counterfactual_edit",
        title="Counterfactual preserve-and-change edits",
        source="Instruction editing / inpaint literature",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/counterfactual/preserve_edit.py",
        summary="Parse 'change X to Y' into locked phrases + regional delta.",
    ),
    ResearchIdea(
        id="uncertainty_gate",
        title="Uncertainty-aware escalation",
        source="Test-time scaling / clarification agents",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/uncertainty/confidence_gate.py",
        summary="Score ambiguous prompts; boost CFG and best-of-N.",
    ),
    ResearchIdea(
        id="inverse_layout",
        title="Image → box layout (inverse)",
        source="LayoutGPT / Omost reverse / VLM bbox",
        url="https://github.com/lllyasviel/Omost",
        status="partial",
        module="frontier/inverse/layout_sketch.py",
        summary="Heuristic color-blob regions; VLM hook planned.",
    ),
    ResearchIdea(
        id="provenance_audit",
        title="Generation provenance bundle",
        source="C2PA / reproducibility best practice",
        url="https://c2pa.org/",
        status="implemented",
        module="frontier/provenance/audit_bundle.py",
        summary="Audit JSON: prompt, seed, args, frontier plan for exact rerun.",
    ),
    ResearchIdea(
        id="fact_rag",
        title="Local style/fact RAG at sample time",
        source="RAG-T2I / SDX superior stack",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/retrieval/fact_rag.py",
        summary="Overlap-ranked JSONL facts injected into prompts.",
    ),
    ResearchIdea(
        id="style_dna",
        title="Prompt-space style DNA blend",
        source="Multi-style without multi-LoRA",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/blend/style_dna.py",
        summary="Interpolate curated style profiles in prompt space.",
    ),
    ResearchIdea(
        id="scene_relations",
        title="Relational scene graph from text",
        source="Scene graph conditioned generation",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/semantics/relation_graph.py",
        summary="Subject-relation-object edges → regional layout hints.",
    ),
    ResearchIdea(
        id="storyboard_chain",
        title="Multi-beat storyboard continuity",
        source="Sequential still / storyboard products",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/temporal/storyboard.py",
        summary="Numbered beats with carry tags and world locks.",
    ),
    ResearchIdea(
        id="token_emphasis",
        title="Hard-token CFG emphasis",
        source="Prompt weighting / counting / text rendering",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/adherence/token_emphasis.py",
        summary="Boost text, hands, counts with (token:weight) fragments.",
    ),
    ResearchIdea(
        id="deep_frontier",
        title="Deep frontier synthesis",
        source="SDX frontier orchestration",
        url="https://github.com/",
        status="implemented",
        module="frontier/synthesis.py",
        summary="Compose plausibility, uncertainty, relations, compute tiers.",
    ),
    ResearchIdea(
        id="multiview_consistency",
        title="Multi-view same-subject consistency",
        source="Zero123 / syncdreamer / view synthesis",
        url="https://arxiv.org/list/cs.CV/recent",
        status="research",
        module="frontier/multiview/",
        summary="Same seed+subject locks across camera azimuth prompts.",
    ),
    ResearchIdea(
        id="latent_navigation",
        title="Concept vector latent navigation",
        source="SDEdit / prompt-to-prompt / latent directions",
        url="https://arxiv.org/list/cs.CV/recent",
        status="research",
        module="frontier/latent/",
        summary="Walk latent space along named concept axes without retrain.",
    ),
    ResearchIdea(
        id="harm_budget",
        title="Safety without creativity collapse",
        source="Adversarial robustness + red-team loops",
        url="https://arxiv.org/list/cs.CV/recent",
        status="research",
        module="innovations/agentic/adversarial.py",
        summary="Graduated refusal vs rewrite instead of hard block.",
    ),
    # --- Subject: bodies, mediums, realism, mature ---
    ResearchIdea(
        id="body_mode_router",
        title="Human vs creature vs mecha body modes",
        source="SDX frontier anatomy",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/anatomy/body_planner.py",
        summary="Route anatomy guidance so dragons are not penalized for extra limbs.",
    ),
    ResearchIdea(
        id="creature_taxonomy",
        title="Species-aware creature body plans",
        source="Fantasy / VFX creature design",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/creatures/taxonomy.py",
        summary="Draconic, insectoid, eldritch limb and surface hints.",
    ),
    ResearchIdea(
        id="mature_quality",
        title="Mature-content render quality",
        source="Adult art / boudoir photography craft",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/mature/mature_guidance.py",
        summary="Skin, lighting, proportion coherence — not censorship.",
    ),
    ResearchIdea(
        id="brush_planner",
        title="Stroke-level medium vocabulary",
        source="Traditional + digital brush craft",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/medium/brush_planner.py",
        summary="Impasto, hatch, spray, calligraphic stroke packs.",
    ),
    ResearchIdea(
        id="extended_mediums",
        title="Extended medium library",
        source="SDX art_mediums expansion",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/medium/extended_mediums.py",
        summary="Spray paint, encaustic, ukiyo-e, risograph, collage, etc.",
    ),
    ResearchIdea(
        id="anti_slop_realism",
        title="Anti-AI-slop photoreal stack",
        source="Uncanny / plastic skin failure modes",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/realism/",
        summary="Lens, sensor, and negative pack against synthetic tells.",
    ),
    ResearchIdea(
        id="subject_frontier",
        title="Subject-aware frontier orchestration",
        source="SDX frontier",
        url="https://github.com/",
        status="implemented",
        module="frontier/subject.py",
        summary="Merge body, creature, mature, medium, brush, photoreal plans.",
    ),
    ResearchIdea(
        id="perfect_frontier",
        title="Perfect frontier (all analyzers)",
        source="SDX frontier",
        url="https://github.com/",
        status="implemented",
        module="frontier/perfect.py",
        summary="Deep + subject + scene quality + safety; --frontier-perfect.",
    ),
    ResearchIdea(
        id="composition_framing",
        title="Composition and framing planner",
        source="Cinematography / design",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/composition/framing.py",
        summary="Rule of thirds, dutch, negative space, layered depth.",
    ),
    ResearchIdea(
        id="motivated_lighting",
        title="Motivated lighting setups",
        source="Portrait / film lighting",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/lighting/motivated_light.py",
        summary="Rembrandt, butterfly, rim, golden hour, neon.",
    ),
    ResearchIdea(
        id="atmosphere_volumetric",
        title="Volumetric atmosphere and weather",
        source="Environmental rendering",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/atmosphere/volumetric.py",
        summary="Fog, god rays, rain, snow, dust haze.",
    ),
    ResearchIdea(
        id="material_surface",
        title="Multi-material surface truth",
        source="PBR / material rendering",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/materials/surface_truth.py",
        summary="Metal, glass, fabric, skin, wood, liquid, hair.",
    ),
    ResearchIdea(
        id="palette_harmony",
        title="Color harmony planner",
        source="Color theory",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/harmony/palette.py",
        summary="Complementary, analogous, triadic, warm/cool.",
    ),
    ResearchIdea(
        id="motion_freeze",
        title="Action freeze and motion blur",
        source="Sports / action photography",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/motion/action_freeze.py",
        summary="Pan blur, impact frames, gravity-readable poses.",
    ),
    ResearchIdea(
        id="era_accuracy",
        title="Historical era accuracy",
        source="Period drama / costume",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/era/period_accuracy.py",
        summary="Anachronism negatives per era.",
    ),
    ResearchIdea(
        id="typography_glyphs",
        title="In-image typography steering",
        source="Ideogram / Imagen text",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/typography/prompt_glyphs.py",
        summary="Quoted text spelling + legibility CFG boost.",
    ),
    ResearchIdea(
        id="lens_character",
        title="Lens personality (anamorphic, fisheye, vintage)",
        source="Optical cinematography",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/optics/lens_character.py",
        summary="Anamorphic oval bokeh, tilt-shift, vintage swirl.",
    ),
    ResearchIdea(
        id="content_policy",
        title="Tiered content policy (pre-gen)",
        source="Platform safety best practice",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/safety/content_policy.py",
        summary="Refuse/steer high-risk prompts; --safety-tier.",
    ),
    # --- Creative (structurally different from prompt stack) ---
    ResearchIdea(
        id="dream_logic",
        title="Surreal / dream logic amplifier",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/surreal/dream_logic.py",
        summary="Amplify intentional impossibility; boosts serendipity dial.",
    ),
    ResearchIdea(
        id="beautiful_paradox",
        title="Keep beautiful paradoxes (Escher, loops)",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/paradox/beautiful_paradox.py",
        summary="Suppress contradiction auto-resolve when paradox intended.",
    ),
    ResearchIdea(
        id="prompt_mutator",
        title="Creative prompt mutations for explore",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/mutation/prompt_mutator.py",
        summary="Time/weather/mood/medium swaps — best-of-N variants.",
    ),
    ResearchIdea(
        id="creative_constraints",
        title="Art-school creative limits",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/constraint/creative_limits.py",
        summary="Monochrome, silhouette, single light, random constraint.",
    ),
    ResearchIdea(
        id="synesthesia_engine",
        title="Music/mood → diffusion knobs",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/synesthesia/cross_modal.py",
        summary="Jazz/techno/etc. tune serendipity + CFG, not just tags.",
    ),
    ResearchIdea(
        id="shot_grammar",
        title="Film director shot grammar",
        source="Cinematography",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/cinema/shot_grammar.py",
        summary="OTS, POV, ECU, worm's eye — director language.",
    ),
    ResearchIdea(
        id="mood_physics",
        title="Mood → serendipity/CFG/step curves",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/vibe/mood_physics.py",
        summary="Ominous/joyful/manic map to numeric sampler physics.",
    ),
    ResearchIdea(
        id="patina_story",
        title="Object weathering narrative",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/weathering/patina.py",
        summary="Rust, repair, graffiti layers as object biography.",
    ),
    ResearchIdea(
        id="glitch_aesthetic",
        title="Intentional glitch aesthetics",
        source="Glitch art",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/glitch/intentional_artifacts.py",
        summary="VHS, datamosh, RGB split as creative choice.",
    ),
    ResearchIdea(
        id="imagination_engine",
        title="Imagination orchestrator",
        source="SDX creative frontier",
        url="https://github.com/",
        status="implemented",
        module="frontier/imagination.py",
        summary="Creative-only stack; --frontier-creative CLI.",
    ),
    ResearchIdea(
        id="genre_fusion",
        title="Genre collision with dominant/accent rule",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/fusion/genre_collision.py",
        summary="Steampunk+cyberpunk etc. without 50/50 mush.",
    ),
    ResearchIdea(
        id="archetype_symbols",
        title="Archetypal symbol anchors",
        source="Mythic / symbolic art",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/archetype/symbol_map.py",
        summary="Threshold, mirror, labyrinth compositional hints.",
    ),
    ResearchIdea(
        id="visual_rhythm",
        title="Visual rhythm and pattern beat",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/rhythm/visual_beat.py",
        summary="Repetition, radial, spiral syncopation.",
    ),
    ResearchIdea(
        id="focal_story",
        title="DOF as emotional storytelling",
        source="Cinematography",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/focal/story_dof.py",
        summary="Isolation, reveal, overwhelm via focus intent.",
    ),
    ResearchIdea(
        id="crowd_grammar",
        title="Crowd diversity without clone faces",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/collective/crowd_grammar.py",
        summary="Group staging and anti-clone negatives.",
    ),
    ResearchIdea(
        id="scale_magnitude",
        title="Titan / miniature / cosmic scale cues",
        source="SDX creative frontier",
        url="https://arxiv.org/list/cs.CV/recent",
        status="implemented",
        module="frontier/scale/magnitude.py",
        summary="Readable size contrast with reference objects.",
    ),
    ResearchIdea(
        id="creative_refine",
        title="Mutation-driven auto-refine",
        source="SDX creative frontier",
        url="https://github.com/",
        status="implemented",
        module="utils/generation/sample_features.py",
        summary="run_creative_refine + --auto-refine with --frontier-creative.",
    ),
    ResearchIdea(
        id="krea_style_refs",
        title="Multi-reference style transfer (Krea 2)",
        source="Krea 2 API",
        url="https://www.krea.ai/blog/krea-2-api-launch",
        status="implemented",
        module="utils/generation/krea_controls.py",
        summary="--style-ref / --style-references-json weighted CLIP blend → reference tokens.",
    ),
    ResearchIdea(
        id="krea_moodboard",
        title="Moodboard aesthetic pooling",
        source="Krea 2 API",
        url="https://www.krea.ai/blog/krea-2-api-launch",
        status="implemented",
        module="utils/generation/krea_controls.py",
        summary="--moodboard-json / --moodboard-images → pooled style embedding.",
    ),
    ResearchIdea(
        id="generative_sliders",
        title="Generative sliders (intensity/complexity/movement)",
        source="Krea Generative Sliders",
        url="https://www.krea.ai/index/generative-sliders",
        status="implemented",
        module="utils/generation/krea_controls.py",
        summary="--slider-intensity/complexity/movement + --creativity-mode.",
    ),
    ResearchIdea(
        id="krea_turbo_preset",
        title="Turbo few-step sampling preset",
        source="Krea 2 Turbo",
        url="https://github.com/krea-ai/krea-2",
        status="implemented",
        module="utils/generation/krea_controls.py",
        summary="--krea-turbo-preset (~8 steps, low CFG).",
    ),
    ResearchIdea(
        id="video_retrieve_compose",
        title="Retrieve → keyframe edit → stitch video",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/pipeline.py",
        summary="T2V/I2V: clip retrieval, keyframe sample.py, interpolate, temporal harmonize.",
    ),
    ResearchIdea(
        id="video_motion_template",
        title="Motion template from reference clips",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/motion.py",
        summary="Optical flow extraction + flow-guided interpolation.",
    ),
    ResearchIdea(
        id="video_provenance",
        title="Video segment provenance log",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/provenance.py",
        summary="Per-segment source/license/operations audit JSON.",
    ),
    ResearchIdea(
        id="video_identity_lock",
        title="Cross-frame identity lock from anchor",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/identity_lock.py",
        summary="Re-composite anchor face/body pixels inside mask or rig box every frame.",
    ),
    ResearchIdea(
        id="video_motion_transfer",
        title="Motion transfer from reference clip",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/motion_transfer.py",
        summary="Warp edited keyframe forward using source optical flow (I2V motion template).",
    ),
    ResearchIdea(
        id="video_pose_control",
        title="Auto-rig pose control maps",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/pose_control.py",
        summary="Stick-figure pose map from auto_rig boxes → sample.py --control-type pose.",
    ),
    ResearchIdea(
        id="video_quality_retry",
        title="Segment quality retry with backoff",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/segment_retry.py",
        summary="Re-run segments on low temporal/sharpness; decay edit strength, boost harmonize.",
    ),
    ResearchIdea(
        id="video_post_grade",
        title="Post color grade presets",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/post_grade.py",
        summary="cinematic | teal_orange | muted | vibrant grades on segment frames.",
    ),
    ResearchIdea(
        id="video_depth_interpolate",
        title="Depth-aware keyframe interpolation",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/depth_interpolate.py",
        summary="Sobel+luminance depth proxy for occlusion-aware mid-frame blends.",
    ),
    ResearchIdea(
        id="video_propagated_identity",
        title="Flow-propagated identity masks",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/identity_lock.py",
        summary="Per-frame mask warp then anchor composite — face/body tracks motion.",
    ),
    ResearchIdea(
        id="video_camera_stabilize",
        title="Reference clip stabilization",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/camera_stabilize.py",
        summary="Cumulative flow compensation before keyframe extraction.",
    ),
    ResearchIdea(
        id="video_deflicker",
        title="Luminance deflicker pass",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/deflicker.py",
        summary="Rolling median exposure match after per-frame img2img edits.",
    ),
    ResearchIdea(
        id="video_motion_beats",
        title="Motion-beat keyframe scheduling",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/motion_beats.py",
        summary="Place keyframe edits on optical-flow peaks in reference footage.",
    ),
    ResearchIdea(
        id="video_flow_consistency",
        title="Forward-backward flow repair",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/flow_consistency.py",
        summary="Blend inconsistent warp pixels toward previous frame.",
    ),
    ResearchIdea(
        id="video_frame_enhance",
        title="Unsharp frame enhancement",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/frame_enhance.py",
        summary="Optional clarity pass after temporal harmonize.",
    ),
    ResearchIdea(
        id="video_audio_mux",
        title="Source audio mux",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/audio_mux.py",
        summary="Extract + concat reference clip audio onto final mp4.",
    ),
    ResearchIdea(
        id="video_transition_fx",
        title="Whip / flash / dip transitions",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/transition_fx.py",
        summary="Extended stitch transitions beyond dissolve and match-action.",
    ),
    ResearchIdea(
        id="video_region_motion",
        title="Per-rig-box regional motion",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/region_motion.py",
        summary="Independent limb/body warp from auto_rig boxes + reference flow.",
    ),
    ResearchIdea(
        id="video_semantic_drift",
        title="Semantic drift detection",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/semantic_drift.py",
        summary="Histogram + structure proxy scores per frame vs anchor.",
    ),
    ResearchIdea(
        id="video_drift_repair",
        title="Automatic drift repair",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/drift_repair.py",
        summary="Blend drifted frames toward neighbors + anchor.",
    ),
    ResearchIdea(
        id="video_velocity_ease",
        title="Velocity ease retiming",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/velocity_curve.py",
        summary="Smoothstep / ease-in / ease-out frame cadence.",
    ),
    ResearchIdea(
        id="video_parallel_segments",
        title="Parallel segment rendering",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/parallel_segments.py",
        summary="ThreadPool segment workers for multi-shot scenes.",
    ),
    ResearchIdea(
        id="video_scene_preflight",
        title="Scene preflight validation",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/scene_preflight.py",
        summary="--preflight checks paths, ckpt, library before run.",
    ),
    ResearchIdea(
        id="video_elements_library",
        title="Elements library (Kling/Runway-style refs)",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/elements.py",
        summary="Tagged multi-ref elements with bind_subject + video_ref in scene JSON.",
    ),
    ResearchIdea(
        id="video_reference_sheet",
        title="Auto reference sheet from one image",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/reference_sheet.py",
        summary="Front/profile/full-body heuristic crops for multi-ref consistency.",
    ),
    ResearchIdea(
        id="video_motion_brush",
        title="Motion brush regional flow",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/motion_brush.py",
        summary="Restrict optical flow to painted/box regions per shot.",
    ),
    ResearchIdea(
        id="video_flf2v",
        title="First-last-frame (FLF2V) shot mode",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/flf2v.py",
        summary="Pin start/end images; interpolate with optional source motion guide.",
    ),
    ResearchIdea(
        id="video_storyboard_cuts",
        title="Storyboard cuts with camera verbs",
        source="SDX video pipeline",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/storyboard.py",
        summary="Kling-style cuts[] → shots with tracking/push_in/orbit prompts.",
    ),
    ResearchIdea(
        id="video_generation_router",
        title="Style generation router",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/generation_router.py",
        summary="auto engine: realistic | anime | pixar_3d | voxel | claymation | …",
    ),
    ResearchIdea(
        id="video_director_mode",
        title="AI Director Mode storyboard expansion",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/director_mode.py",
        summary="One prompt → multi-shot cuts + director notes; edit before gen.",
    ),
    ResearchIdea(
        id="video_style_engines",
        title="Multi-engine presets",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/style_engines.py",
        summary="Per-style edit overrides, prompts, animation presets, layer hints.",
    ),
    ResearchIdea(
        id="video_character_world_memory",
        title="Character + world bibles",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/character_memory.py",
        summary="Persistent Alex/world rules across episodes and engines.",
    ),
    ResearchIdea(
        id="video_motion_library_packs",
        title="Motion pack library",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/motion_library.py",
        summary="Decouple motion clips from appearance; mix packs per shot.",
    ),
    ResearchIdea(
        id="video_animation_principles",
        title="Disney principles sliders",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/animation_principles.py",
        summary="Pixar/Ghibli/Looney presets + squash/anticipation/timing prompts.",
    ),
    ResearchIdea(
        id="video_camera_rig",
        title="Virtual camera rig",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/camera_rig.py",
        summary="ARRI/drone/VHS/anime operator presets → prompt + fps.",
    ),
    ResearchIdea(
        id="video_director_personalities",
        title="Director personality presets",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/director_personalities.py",
        summary="Spielberg, Nolan, Miyazaki, horror — cinematic bias injection.",
    ),
    ResearchIdea(
        id="video_rehearsal_pipeline",
        title="Rehearsal stages (animatic → full)",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/rehearsal_pipeline.py",
        summary="Cheap animatic/low-poly passes before full GPU render.",
    ),
    ResearchIdea(
        id="video_layer_stack",
        title="Layer-based style routing",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/layer_stack.py",
        summary="Background realistic + character anime hybrid via layer_stack.",
    ),
    ResearchIdea(
        id="video_thumbnail_rehearsal",
        title="Thumbnail-first rehearsal gate",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/thumbnail_rehearsal.py",
        summary="Cheap 128px composition pass; require_approval gate before full render.",
    ),
    ResearchIdea(
        id="video_continuity_validators",
        title="Continuity validators (eyeline, props, light)",
        source="SDX video studio",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/continuity_validators.py",
        summary="Eyeline 180°, prop ledger, motivated lighting, silhouette readability.",
    ),
    ResearchIdea(
        id="video_tension_thermostat",
        title="Narrative Tension Thermostat",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/narrative_tension.py",
        summary="Emotion curve per shot drives camera, motion, and grade.",
    ),
    ResearchIdea(
        id="video_causal_ripple",
        title="Causal Ripple Engine",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/causal_events.py",
        summary="Story triggers (explosion, thunder) auto-inject FX and camera reactions.",
    ),
    ResearchIdea(
        id="video_anticipation_borrow",
        title="Anticipation Borrow",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/anticipation_windup.py",
        summary="Steals shot duration for Disney-style pre-action wind-up.",
    ),
    ResearchIdea(
        id="video_motif_haunting",
        title="Motif Haunting",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/motif_tracker.py",
        summary="Visual symbols persist in frame until narratively resolved.",
    ),
    ResearchIdea(
        id="video_kinetic_ledger",
        title="Kinetic Ledger",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/kinetic_continuity.py",
        summary="Cross-shot energy conservation and landing beats.",
    ),
    ResearchIdea(
        id="video_narrative_spotlight",
        title="Narrative Spotlight / fog of narrative",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/diegetic_focus.py",
        summary="Hero detail vs impressionistic periphery per shot.",
    ),
    ResearchIdea(
        id="video_temporal_echo",
        title="Temporal Echo rhymes",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/temporal_echo.py",
        summary="Shots visually rhyme with earlier beats automatically.",
    ),
    ResearchIdea(
        id="video_semantic_gravity",
        title="Semantic Gravity wells",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/semantic_gravity.py",
        summary="Narrative weight → identity lock and drift repair priority.",
    ),
    ResearchIdea(
        id="video_breath_cadence",
        title="Breath Cadence micro-motion",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/breath_cadence.py",
        summary="Breathing amplitude synced to tension thermostat.",
    ),
    ResearchIdea(
        id="video_what_if_timeline",
        title="What-If Timeline branches",
        source="SDX frontier video",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/counterfactual_beats.py",
        summary="Parallel alternate shot branches for exploration.",
    ),
    ResearchIdea(
        id="sdx_tension_field",
        title="Tension Field (image diffusion)",
        source="SDX frontier",
        url="https://github.com/",
        status="implemented",
        module="frontier/narrative/tension_field.py",
        summary="Tension → step emphasis curve + CFG boost for keyframes.",
    ),
    ResearchIdea(
        id="sdx_video_frontier_bridge",
        title="Cinema video bridge",
        source="SDX frontier",
        url="https://github.com/",
        status="implemented",
        module="frontier/cinema/video_bridge.py",
        summary="Unifies SDX image frontier + video frontier for keyframe prompts.",
    ),
    ResearchIdea(
        id="video_screen_direction_lock",
        title="Screen Direction Lock",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/screen_direction.py",
        summary="Movement vector 180° rule across cuts.",
    ),
    ResearchIdea(
        id="video_offscreen_space",
        title="Offscreen Space Map",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/offscreen_space.py",
        summary="Off-frame zones inject audio, light, and reactions.",
    ),
    ResearchIdea(
        id="video_emotional_contagion",
        title="Emotional Contagion",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/emotional_contagion.py",
        summary="Background crowd inherits hero emotion.",
    ),
    ResearchIdea(
        id="video_material_memory",
        title="Material Memory",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/material_memory.py",
        summary="Wet/mud/blood persists until cleaned.",
    ),
    ResearchIdea(
        id="video_camera_empathy",
        title="Camera Empathy",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/camera_empathy.py",
        summary="Camera retreats, lingers, trembles with subject.",
    ),
    ResearchIdea(
        id="video_weather_inertia",
        title="Weather Inertia",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/weather_inertia.py",
        summary="Climate state persists across cuts.",
    ),
    ResearchIdea(
        id="video_narrative_debt",
        title="Narrative Debt tracker",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/narrative_debt.py",
        summary="Plot threads must pay off by deadline shot.",
    ),
    ResearchIdea(
        id="video_chromatic_arc",
        title="Chromatic Story Arc",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/chromatic_arc.py",
        summary="Color script evolves with story emotion.",
    ),
    ResearchIdea(
        id="video_stinger_frames",
        title="Stinger Frames",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/stinger_frames.py",
        summary="Impact/sakuga emphasis on last N frames.",
    ),
    ResearchIdea(
        id="video_witness_lens",
        title="Witness Lens",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/witness_lens.py",
        summary="Embodied viewpoint changes framing per shot.",
    ),
    ResearchIdea(
        id="video_silence_map",
        title="Silence Map",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/silence_map.py",
        summary="Deliberate audio/visual silence beats.",
    ),
    ResearchIdea(
        id="video_scar_timeline",
        title="Scar Timeline",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/scar_timeline.py",
        summary="Injuries accumulate on characters across shots.",
    ),
    ResearchIdea(
        id="video_parallax_budget",
        title="Parallax Depth Budget",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="pipelines/video/parallax_budget.py",
        summary="2.5D layer separation for compositing.",
    ),
    ResearchIdea(
        id="sdx_chromatic_field",
        title="Chromatic Field (image)",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="frontier/narrative/chromatic_field.py",
        summary="Palette bias for keyframe diffusion.",
    ),
    ResearchIdea(
        id="sdx_absence_pulse",
        title="Absence Pulse (image)",
        source="SDX frontier wave 2",
        url="https://github.com/",
        status="implemented",
        module="frontier/cinema/absence_pulse.py",
        summary="Negative-space amplification for horror/minimal beats.",
    ),
]


def list_ideas(*, status: Status | None = None) -> List[ResearchIdea]:
    if status is None:
        return list(IDEAS)
    return [i for i in IDEAS if i.status == status]


def idea_by_id(idea_id: str) -> ResearchIdea:
    key = (idea_id or "").strip().lower()
    for i in IDEAS:
        if i.id == key:
            return i
    raise KeyError(f"unknown idea {idea_id!r}")


def ideas_summary_markdown() -> str:
    lines = ["| ID | Status | Module |", "|----|--------|--------|"]
    for i in IDEAS:
        lines.append(f"| `{i.id}` | {i.status} | `{i.module}` |")
    return "\n".join(lines)


__all__ = [
    "IDEAS",
    "ResearchIdea",
    "idea_by_id",
    "ideas_summary_markdown",
    "list_ideas",
]
